# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
DrinkTool.destroy_all
DrinkIngredient.destroy_all
DrinkGenre.destroy_all

Genre.destroy_all

alternative_rock = Genre.create('name': 'alternative rock')
remix = Genre.create('name': 'remix')
british = Genre.create('name': 'british')
spanish_pop = Genre.create('name': 'spanish pop')
neo_psychadelic = Genre.create('name': 'neo-psychadelic')
psychadelic_rock = Genre.create('name': 'psychadelic rock')
glam_metal = Genre.create('name': 'glam metal')
latin_pop = Genre.create('name': 'latin pop')
grupera = Genre.create('name': 'grupera')
pop = Genre.create('name': 'pop')
focus = Genre.create('name': 'focus')
synth_pop = Genre.create('name': 'synthpop')
deep_house = Genre.create('name': 'deep house')
emo = Genre.create('name': 'emo')
punk = Genre.create('name': 'punk')
hardcore = Genre.create('name': 'hardcore')
rock = Genre.create('name': 'rock')
metal = Genre.create('name': 'metal')
rap = Genre.create('name': 'rap')
post_teen_pop = Genre.create('name': 'post-teen pop')
viral_pop = Genre.create('name': 'viral pop')
edm = Genre.create('name': 'edm')
disco = Genre.create('name': 'disco')
house = Genre.create('name': 'house')
techno = Genre.create('name': 'techno')
salsa = Genre.create('name': 'salsa')
folk = Genre.create('name': 'folk')
regional_mexican = Genre.create('name': 'regional mexican')
latin = Genre.create('name': 'Latin')
black_metal = Genre.create('name': 'black metal')
death_metal = Genre.create('name': 'death metal')
trap_francais = Genre.create('name': 'trap francais')
metalcore = Genre.create('name': 'metalcore')
hard_stoner_rock = Genre.create('name': 'hard stoner rock')
spanish = Genre.create('name': 'spanish')
latin_rock = Genre.create('name': 'latin rock')
cabaret = Genre.create('name': 'cabaret')
r_b = Genre.create('name': 'R&B')
hip_hop = Genre.create('name': 'hip hop')
smooth_jazz = Genre.create('name': 'smooth jazz')
quiet_storm = Genre.create('name': 'quiet storm')
blues = Genre.create('name': 'blues')
soul_blues = Genre.create('name': 'soul blues')
southern = Genre.create('name': 'southern')
traditional_jazz = Genre.create('name': 'traditional jazz')
jazz = Genre.create('name': 'jazz')
classical = Genre.create('name': 'classical')
cajun = Genre.create('name': 'cajun')
new_orleans_jazz = Genre.create('name': 'new orleans jazz')
ragtime = Genre.create('name': 'ragtime')
dixieland = Genre.create('name': 'dixieland')
new_jack_swing = Genre.create('name': 'new jack swing')
neo_soul = Genre.create('name': 'neo soul')
indie_rock = Genre.create('name': 'indie rock')
new_americana = Genre.create('name': 'new americana')
americana = Genre.create('name': 'americana')
indie_anthem_folk = Genre.create('name': 'indie anthem folk')
folk_punk = Genre.create('name': 'folk punk')
gypsy_punk = Genre.create('name': 'gypsy punk')
bluegrass = Genre.create('name': 'bluegrass')
piano_rock = Genre.create('name': 'piano rock')
improvisational_jazz = Genre.create('name': 'improvisational jazz')
post_bop = Genre.create('name': 'post bop')
adult_standards = Genre.create('name': 'adult standards')
crooner_jazz = Genre.create('name': 'crooner jazz')
acoustic_pop = Genre.create('name': 'acoustic pop')
modern_rock = Genre.create('name': 'modern rock')
album_rock = Genre.create('name': 'album rock')
mellow_gold = Genre.create('name': 'mellow gold')
singer_songwriter = Genre.create('name': 'singer-songwriter')
modern_blues = Genre.create('name': 'modern blues')
lofi = Genre.create('name': 'lo-fi')
garage_rock = Genre.create('name': 'garage rock')
hard_rock = Genre.create('name': 'hard rock')
chillwave = Genre.create('name': 'chillwave')
freak_folk = Genre.create('name': 'freak folk')
country = Genre.create('name': 'country')
indie_folk = Genre.create('name': 'indie folk')
new_wave = Genre.create('name': 'new wave')
progressive = Genre.create('name': 'progressive')
british_blues = Genre.create('name': 'british blues')
rock_roll = Genre.create('name': 'rock-and-roll')
classic_rock = Genre.create('name': 'classic rock')
britpop = Genre.create('name': 'britpop')
ska = Genre.create('name': 'ska')
funk = Genre.create('name': 'funk')
drumline = Genre.create('name': 'drumline')
country_road = Genre.create('name': 'country road')
stomp_holler = Genre.create('name': 'Stomp & Holler')
mexican_pop = Genre.create('name': 'mexican pop')
compositional_ambient = Genre.create('name': 'compositional ambient')
ballads = Genre.create('name': 'ballads')
vintage_jazz = Genre.create('name': 'vintage jazz')
southern_soul = Genre.create('name': 'southern soul')
french = Genre.create('name': 'french')
acoustic_pop = Genre.create('name': 'acoustic pop')
indie_rb = Genre.create('name': 'indie r&b')
gypsy_folk = Genre.create('name': 'gypsy folk')
greek = Genre.create('name': 'greek')
rebetika = Genre.create('name': 'rebetika')
motown = Genre.create('name': 'MoTown')
art_pop = Genre.create('name': 'art pop')
christian_music = Genre.create('name': 'christian music')
jazz_blues = Genre.create('name': 'jazz blues')
underground_hip_hop = Genre.create('name': 'underground hip hop')
dirty_south_hip_hop = Genre.create('name': 'dirth south hip hop')
french_hip_hop = Genre.create('name': 'french hip hop')
southern_hip_hop = Genre.create('name': 'southern hip hop')
trap_music = Genre.create('name': 'trap music')
tropical = Genre.create('name': 'tropical')
japanese_city_pop = Genre.create('name': 'japanese city pop')
k_hop = Genre.create('name': 'k-hop')
j_poprock = Genre.create('name': 'k-hop')



Artist.destroy_all

thrice = Artist.create('name': 'Thrice')

ArtistGenre.create('artist_id': thrice.id, 'genre_id': punk.id)
ArtistGenre.create('artist_id': thrice.id, 'genre_id': rock.id)
ArtistGenre.create('artist_id': thrice.id, 'genre_id': metal.id)

Tool.destroy_all

blender = Tool.create('name': 'Blender')
strainer = Tool.create('name': 'Strainer')
bar_spoon = Tool.create('name': 'Bar Spoon')
boston_shaker = Tool.create('name': 'Boston Shaker')
hawthorne_strainer = Tool.create('name': 'Hawthorne Strainer')
zester = Tool.create('name': 'Zester/Grater')
jigger = Tool.create('name': 'Jigger')
mixing_glass = Tool.create('name': 'Mixing Glass')
citrus_peeler = Tool.create('name': 'Citrus Peeler')
glass_rimmer = Tool.create('name': 'Glass Rimmer')
fruit_pick = Tool.create('name': 'Fruit Pick')
muddler = Tool.create('name': 'Muddler')
pint_glass = Tool.create('name': 'Pint Glass')
julep_strainer = Tool.create('name': 'Julep Strainer')
punch_bowl = Tool.create('name': 'Punch bowl')
ladle = Tool.create('name': 'Ladle')
highball_glass = Tool.create('name': 'Highball glass')
peeler = Tool.create('name': 'Peeler')
lewis_bag = Tool.create('name': 'Lewis bag')
mallet = Tool.create('name': 'Mallet')
straw = Tool.create('name': 'Straw')
shaker_tins = Tool.create('name': 'Shaker Tins')
collins_glass = Tool.create('name': 'Collins Glass')
glass = Tool.create('name': 'Glass')
pitcher = Tool.create('name': 'Pitcher')
knife = Tool.create('name': 'Knife')





Ingredient.destroy_all

spice_base = 'Spice Base'
horseradish = 'Ground Horseradish'
tomato_juice = 'Tomato Juice'
apple_brandy = 'Copper & Kings Un-Aged Apple Brandy'

immature_brandy = 'Immature Brandy'
lime_juice = 'Freshly squeezed lime juice'
angostura_bitters = 'angostura bitters'


club_soda = Ingredient.create('name': 'Club Soda')
two_club_soda = Ingredient.create('name': 'Club Soda', 'amount': 2)
tonic = Ingredient.create('name': 'Tonic')
lime = Ingredient.create('name': 'Lime')
mint = Ingredient.create('name': 'Mint')
lemon = Ingredient.create('name': 'Lemon')
celery = Ingredient.create('name': 'Celery')
olives = Ingredient.create('name': 'Olives')
peppers = Ingredient.create('name': 'Peppers')
citrus = Ingredient.create('name': 'Citrus')
meat = Ingredient.create('name': 'Meat')
two_apple_brandy = Ingredient.create('name': apple_brandy, 'amount': 2, 'unit': 'oz')
four_tomato_juice = Ingredient.create('name': tomato_juice, 'amount': 4, 'unit': 'oz')
one_spice_base = Ingredient.create('name': spice_base, 'amount': 1, 'unit': 'oz')
one_horseradish = Ingredient.create('name': horseradish, 'amount': 1, 'unit': 'tsp')
ginger_ale = Ingredient.create('name': 'Ginger Ale')
two_immature = Ingredient.create('name': immature_brandy, 'amount': 2, 'unit': 'oz')
sm_lime = Ingredient.create('name': lime_juice, 'amount': 0.25, 'unit': 'oz')
three_angs = Ingredient.create('name': angostura_bitters, 'amount': 3, 'unit': 'drops')
red_table_wine = Ingredient.create('name': 'Red table win', 'amount': 750, 'unit': 'ML')
sprig_mint = Ingredient.create('name': 'Sprig of mint')
two_mixed_berry = Ingredient.create('name': 'Mixed Berries', 'amount': 2, 'unit': 'cups')
grapefruit = Ingredient.create('name': 'Grapefruit, sliced', 'amount': 1)
lemon_sliced = Ingredient.create('name': 'Lemon, thinly sliced', 'amount': 1)
quarter_honey = Ingredient.create('name': 'Honey', 'amount': 0.25, 'unit': 'cup')
american_brandy = Ingredient.create('name': 'American craft brandy', 'amount': 0.25, 'unit': 'cup')
absinthe_blanche = Ingredient.create('name': 'Copper & Kings Absinthe Blanche', 'amount': 1, 'unit': 'oz')
superfine_sugar = Ingredient.create('name': 'Superfine Sugar', 'amount': 0.5, 'unit': 'tsp')
one_water = Ingredient.create('name': 'Water', 'amount': 1, 'unit': 'oz')
absinthe_blanche_onefive = Ingredient.create('name': 'Copper & Kings Absinthe Blanche', 'amount': 1.5, 'unit': 'oz')
brut_champagne = Ingredient.create('name': 'Brut Champagne', 'amount': 4, 'unit': 'oz')
american_gin = Ingredient.create('name': 'American Dry Gin', 'amount': 2, 'unit': 'oz')
four_tonic = Ingredient.create('name': 'Tonic Water', 'amount': 4, 'unit': 'oz')
two_american_brandy = Ingredient.create('name': 'Copper & Kings American Craft Brandy', 'amount': 2, 'unit': 'oz')
creme_cacao = Ingredient.create('name': 'Crème de Cacao', 'amount': 0.75, 'unit': 'oz')
cream = Ingredient.create('name': 'Cream', 'amount': 0.75, 'unit': 'oz')
grated_nutmeg = Ingredient.create('name': 'Freshly grated nutmeg')
maraschino_liqueur = Ingredient.create('name': 'Maraschino liqueur (Luxardo)', 'amount': 1, 'unit': 'tsp')
lemon_juice = Ingredient.create('name': 'Fresh lemon juice', 'amount': 0.5, 'unit': 'tsp')
demerara_syrup = Ingredient.create('name': 'Bar spoon of demerara syrup (we use 2:1)')
pehchauds_bitters = Ingredient.create('name': 'peychaud’s bitters', 'amount': 2, 'unit': 'dashes')
crushed_ice = Ingredient.create('name': 'Crushed Ice')
onefive_american_brandy = Ingredient.create('name': 'Copper & Kings American Craft Brandy', 'amount': 1.5, 'unit': 'oz')
half_gin = Ingredient.create('name': 'Gin', 'amount': 0.5, 'unit': 'oz')
lemon_juice75 = Ingredient.create('name': 'Freshly squeezed lemon juice', 'amount': 0.75, 'unit': 'oz')
orgeat75 = Ingredient.create('name': 'Orgeat', 'amount': 0.75, 'unit': 'oz')
superfine_whole = Ingredient.create('name': 'Superfine sugar')
orange_wedge_twist = Ingredient.create('name': 'Large orange wedge and twist')
one_american_brandy = Ingredient.create('name': 'Copper & Kings American Brandy', 'amount': 1, 'unit': 'oz')
one_tom_gin = Ingredient.create('name': 'Copper & Kings American Old Tom Gin', 'amount': 1, 'unit': 'oz')
one_vermouth = Ingredient.create('name': 'Sweet Vermouth', 'amount': 1, 'unit': 'oz')
bittermens = Ingredient.create('name': 'Bittermens Amere Sauvage (Or, Substitute: 2 Dashes Orange Bitters)', 'amount': 0.25, 'unit': 'oz')
destillare = Ingredient.create('name': 'Destillaré Orange Curaçao To Top')
sugar_cube = Ingredient.create('name': 'Sugar cube', 'amount': 1)
two_angs = Ingredient.create('name': 'Angotsura bitters', 'amount': 2, 'unit': 'dashes')
thick_orange_wedge = Ingredient.create('name': 'Thick slice orange wedge', 'amount': 1)
one_amarena = Ingredient.create('name': 'Amarena/Maraska Cherry', 'amount': 1)
one_apple_brandy = Ingredient.create('name': apple_brandy, 'amount': 1, 'unit': 'oz')
three_absinthe_blanche = Ingredient.create('name': 'Copper & Kings Absinthe Blanche', 'amount': 3, 'unit': 'dashes')
one_benedictine = Ingredient.create('name': 'Bénédictine', 'amount': 1, 'unit': 'oz')
two_french_vermouth = Ingredient.create('name': 'French vermouth', 'amount': 2, 'unit': 'oz')
orange_peel = Ingredient.create('name': 'Orange Peel')
orange_liqueur75 = Ingredient.create('name': 'Orange liqueur (dry curacao or Cointreau)', 'amount': 0.75, 'unit': 'oz')
lg_lime = Ingredient.create('name': lime_juice, 'amount': 0.75, 'unit': 'oz')
lg_american_brandy = Ingredient.create('name': 'Copper & Kings American Craft Brandy', 'amount': 8, 'unit': 'oz')
lg_peach_liqueur = Ingredient.create('name': 'Peach liqueur (Mathilde, Rothman & Winter)', 'amount': 4, 'unit': 'oz')
lg_jamaican_rum = Ingredient.create('name': 'Jamaican rum (Blackwell, Appleton, Smith & Cross)', 'amount': 4, 'unit': 'oz')
xlg_lime = Ingredient.create('name': lime_juice, 'amount': 6, 'unit': 'oz')
simple_syrup = Ingredient.create('name': '1:1 simple syrup', 'amount': 4, 'unit': 'oz')
lg_filtered_water = Ingredient.create('name': 'Filtered water frozen into large ice block', 'amount': 16, 'unit': 'oz')
lemon_peels = Ingredient.create('name': 'Lemon Peels')
four_ginger_beer = Ingredient.create('name': 'Ginger Beer', 'amount': 4, 'unit': 'oz')
one_ang = Ingredient.create('name': 'Angotsura bitters', 'amount': 1, 'unit': 'dash')
grenadine = Ingredient.create('name': 'Grenadine', 'amount': 0.75, 'unit': 'oz')
half_simple_syrup = Ingredient.create('name': 'Simple Syrup', 'amount': 0.5, 'unit': 'oz')
mint_leaves = Ingredient.create('name': '8-10 Mint Leaves')
casa_noble = Ingredient.create('name': 'Casa Noble Blanco Tequila', 'amount': 2, 'unit': 'oz')
ofive_destillare = Ingredient.create('name': 'Destillaré Intense Orange Curaçao', 'amount': 0.5, 'unit': 'oz')
quarter_simple_syrup = Ingredient.create('name': 'Simple Syrup', 'amount': 0.25, 'unit': 'oz')
med_lime = Ingredient.create('name': lime_juice, 'amount': 0.5, 'unit': 'oz')
lime_wedge = Ingredient.create('name': 'Lime wedge, garnish')
three_peychauds_bitters = Ingredient.create('name': 'Peychaud’s bitters', 'amount': 3, 'unit': 'dashes')
demerara_cube = Ingredient.create('name': 'Demerara Sugar Cube', 'amount': 1)
absinthe_rinse = Ingredient.create('name': 'Absinthe Rinse')
lemon_twist = Ingredient.create('name': 'Lemon Twist')
one_lime = Ingredient.create('name': lime_juice, 'amount': 1, 'unit': 'oz')
lime_wheel = Ingredient.create('name': 'Lime Wheel')
lemon_wheel = Ingredient.create('name': 'Lemon Wheel')
half_egg = Ingredient.create('name': 'Fresh egg white', 'amount': 0.5, 'unit': 'oz')
one_simple_syrup = Ingredient.create('name': '2:1 simple syrup', 'amount': 1, 'unit': 'oz')
one_lemon_juice = Ingredient.create('name': 'Fresh lemon juice', 'amount': 1, 'unit': 'oz')
ice_water = Ingredient.create('name': 'Ice cold water')
one_high_west = Ingredient.create('name': 'High West Double Rye Whiskey', 'amount': 1, 'unit': 'oz')
half_benedictine = Ingredient.create('name': 'Benedictine', 'amount': 0.5, 'unit': 'oz')
twist_orange = Ingredient.create('name': 'Twist of Orange')
brandied_cherry = Ingredient.create('name': 'Brandied Cherry')
two_orange_bitters = Ingredient.create('name': 'Orange Bitters', 'amount': 2, 'unit': 'dashes')
one_orgeat = Ingredient.create('name': 'Orgeat Syrup', 'amount': 1, 'unit': 'tbsp')
four_angs = Ingredient.create('name': 'Angotsura Bitters', 'amount': 4, 'unit': 'dashes')



Drink.destroy_all

japanese_image = File.open('app/assets/images/japanese.jpg')
japanese = Drink.create('name': 'Japanese Cocktail', 'directions': 'Fill the mixing glass ⅓ full of ice, add ingredients and stir with spoon. Strain into chilled coupe. Garnish with a lemon peel.',
'image': japanese_image)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': deep_house.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': tropical.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': japanese_city_pop.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': k_hop.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': j_poprock.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': edm.id)
DrinkIngredient.create('drink_id': japanese.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': japanese.id, 'ingredient_id': one_orgeat.id)
DrinkIngredient.create('drink_id': japanese.id, 'ingredient_id': four_angs.id)
DrinkTool.create('drink_id': japanese.id, 'tool_id': strainer.id)
DrinkTool.create('drink_id': japanese.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': japanese.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': japanese.id, 'tool_id': knife.id)
#
# marconi_wireless_image = File.open('app/assets/images/marconieWireless.jpg')
# marconi_wireless = Drink.create('name': 'The Marconi Wireless', 'directions': 'Stir, strain into a chilled cocktail glass.  Garnish with either a cherry or a lemon peel.',
# 'image': marconi_wireless_image)
# DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': modern_rock.id)
# DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': garage_rock.id)
# DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': freak_folk.id)
# DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': lofi.id)
# DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': compositional_ambient.id)
# DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': focus.id)
# DrinkIngredient.create('drink_id': marconi_wireless.id, 'ingredient_id': two_apple_brandy.id)
# DrinkIngredient.create('drink_id': marconi_wireless.id, 'ingredient_id': one_vermouth.id)
# DrinkIngredient.create('drink_id': marconi_wireless.id, 'ingredient_id': two_orange_bitters.id)
# DrinkTool.create('drink_id': marconi_wireless.id, 'tool_id': jigger.id)
# DrinkTool.create('drink_id': marconi_wireless.id, 'tool_id': mixing_glass.id)
# DrinkTool.create('drink_id': marconi_wireless.id, 'tool_id': bar_spoon.id)
# DrinkTool.create('drink_id': marconi_wireless.id, 'tool_id': hawthorne_strainer.id)
#
# vieux_carre_image = File.open('app/assets/images/vieuxCarre.jpg')
# vieux_carre = Drink.create('name': 'Vieux Carré', 'directions': 'Combine ingredients in mixing glass and fill with ice. Stir well, strain into an ice-filled cocktail glass and garnish with a brandied cherry, lemon twist or both.',
# 'image': vieux_carre_image)
# DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': jazz_blues.id)
# DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': underground_hip_hop.id)
# DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': dirty_south_hip_hop.id)
# DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': french_hip_hop.id)
# DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': southern_hip_hop.id)
# DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': trap_music.id)
# DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': one_american_brandy.id)
# DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': one_high_west.id)
# DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': one_vermouth.id)
# DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': half_benedictine.id)
# DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': two_angs.id)
# DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': pehchauds_bitters.id)
# DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': twist_orange.id)
# DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': brandied_cherry.id)
# DrinkTool.create('drink_id': vieux_carre.id, 'tool_id': mixing_glass.id)
# DrinkTool.create('drink_id': vieux_carre.id, 'tool_id': bar_spoon.id)
# DrinkTool.create('drink_id': vieux_carre.id, 'tool_id': julep_strainer.id)
#
# the_ritual_image = File.open('app/assets/images/theRitual.jpg')
# the_ritual = Drink.create('name': 'The Ritual', 'directions': 'Add Absinthe to glass. Slowly drizzle a trickle of ice cold water to the spirit watching closely as it mixes with the Absinthe. When the water to absinthe ratio reaches somewhere between 1:3 & 1:5 (depending on your taste), the essential oils which are dissolved in the absinthe during distillation will emulsify with the water and create the translucent cloudy effect known as the "louche."',
# 'image': the_ritual_image, 'tips': 'Due to the exquisite nature of our craft absinthe we do not ascribe to the traditional use of sugar. As with everything, we’ll leave it to your personal taste.')
# DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': death_metal.id)
# DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': psychadelic_rock.id)
# DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': chillwave.id)
# DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': christian_music.id)
# DrinkIngredient.create('drink_id': the_ritual.id, 'ingredient_id': absinthe_blanche_onefive.id)
# DrinkIngredient.create('drink_id': the_ritual.id, 'ingredient_id': ice_water.id)
# DrinkTool.create('drink_id': the_ritual.id, 'tool_id': glass.id)
# DrinkTool.create('drink_id': the_ritual.id, 'tool_id': pitcher.id)
#
# standard_collins_image = File.open('app/assets/images/standardCollins.jpg')
# standard_collins = Drink.create('name': 'Standard (Tom) Collins', 'directions': 'Combine brandy, lemon juice, and syrup in shaker tin, shake with ice. Strain into collins glass, add fresh ice, top with soda. Garnish with lemon wheel.',
# 'image': standard_collins_image, 'tips': 'Fresh lemon juice (less than 8 hours old) works best in this recipe.')
# DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': motown.id)
# DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': synth_pop.id)
# DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': art_pop.id)
# DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': two_immature.id)
# DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': one_lemon_juice.id)
# DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': one_simple_syrup.id)
# DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': lemon_wheel.id)
# DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': two_club_soda.id)
# DrinkTool.create('drink_id': standard_collins.id, 'tool_id': shaker_tins.id)
# DrinkTool.create('drink_id': standard_collins.id, 'tool_id': hawthorne_strainer.id)
# DrinkTool.create('drink_id': standard_collins.id, 'tool_id': jigger.id)
# DrinkTool.create('drink_id': standard_collins.id, 'tool_id': collins_glass.id)
#
# brandy_sour_image = File.open('app/assets/images/brandySour.jpg')
# brandy_sour = Drink.create('name': 'Brandy Sour', 'directions': 'Add all the ingredients to a Boston shaker and fill with ice. Shake vigorously and strain into a rocks glass. Garnish with a lime wheel and 3 gentle drops of angostura bitters, which will settle in the foam of the cocktail. Using a straw, swirl the bitters into a simple design.',
# 'image': brandy_sour_image, 'tips': 'Remove the whisk from the hawthorn strainer and place it into the mixing glass prior to shaking for added aeration.')
# DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': acoustic_pop.id)
# DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': indie_rb.id)
# DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': gypsy_folk.id)
# DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': greek.id)
# DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': rebetika.id)
# DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': two_immature.id)
# DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': one_lime.id)
# DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': one_simple_syrup.id)
# DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': lime_wheel.id)
# DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': half_egg.id)
# DrinkTool.create('drink_id': brandy_sour.id, 'tool_id': boston_shaker.id)
# DrinkTool.create('drink_id': brandy_sour.id, 'tool_id': hawthorne_strainer.id)
# DrinkTool.create('drink_id': brandy_sour.id, 'tool_id': straw.id)

# sazerac_image = File.open('app/assets/images/sazerac.jpg')
# sazerac = Drink.create('name': 'Sazerac', 'directions': 'Muddle the sugar and bitters, then add the Brandy and ice. Stir and strain into a chilled, Absinthe rinsed rocks glass. Twist a Lemon Peel over the surface and discard.',
# 'image': sazerac_image)
# DrinkGenre.create('drink_id': sazerac.id, 'genre_id': southern.id)
# DrinkGenre.create('drink_id': sazerac.id, 'genre_id': hip_hop.id)
# DrinkGenre.create('drink_id': sazerac.id, 'genre_id': ragtime.id)
# DrinkGenre.create('drink_id': sazerac.id, 'genre_id': jazz.id)
# DrinkGenre.create('drink_id': sazerac.id, 'genre_id': vintage_jazz.id)
# DrinkGenre.create('drink_id': sazerac.id, 'genre_id': new_orleans_jazz.id)
# DrinkGenre.create('drink_id': sazerac.id, 'genre_id': southern_soul.id)
# DrinkGenre.create('drink_id': sazerac.id, 'genre_id': french.id)
# DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': two_american_brandy.id)
# DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': three_peychauds_bitters.id)
# DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': demerara_cube.id)
# DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': absinthe_rinse.id)
# DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': lemon_twist.id)
# DrinkTool.create('drink_id': sazerac.id, 'tool_id': muddler.id)
# DrinkTool.create('drink_id': sazerac.id, 'tool_id': mixing_glass.id)
# DrinkTool.create('drink_id': sazerac.id, 'tool_id': bar_spoon.id)
# DrinkTool.create('drink_id': sazerac.id, 'tool_id': strainer.id)


# mule_image = File.open('app/assets/images/mule.jpg')
# mule = Drink.create('name': 'Mule', 'directions': 'Combine all ingredients in highball glass, add ice. Garnish with lime wedge.',
# 'image': mule_image)
# DrinkGenre.create('drink_id': mule.id, 'genre_id': new_wave.id)
# DrinkGenre.create('drink_id': mule.id, 'genre_id': alternative_rock.id)
# DrinkGenre.create('drink_id': mule.id, 'genre_id': remix.id)
# DrinkGenre.create('drink_id': mule.id, 'genre_id': british.id)
# DrinkGenre.create('drink_id': mule.id, 'genre_id': punk.id)
# DrinkGenre.create('drink_id': mule.id, 'genre_id': garage_rock.id)
# DrinkGenre.create('drink_id': mule.id, 'genre_id': album_rock.id)
# DrinkIngredient.create('drink_id': mule.id, 'ingredient_id': two_immature.id)
# DrinkIngredient.create('drink_id': mule.id, 'ingredient_id': med_lime.id)
# DrinkIngredient.create('drink_id': mule.id, 'ingredient_id': four_ginger_beer.id)
# DrinkIngredient.create('drink_id': mule.id, 'ingredient_id': lime_wedge.id)
# DrinkTool.create('drink_id': mule.id, 'tool_id': jigger.id)
# DrinkTool.create('drink_id': mule.id, 'tool_id': highball_glass.id)

# metropolitan_image = File.open('app/assets/images/metropolitan.jpg')
# metropolitan = Drink.create('name': 'Metropolitan', 'directions': 'Combine ingredients in mixing glass. Add ice. Stir until well chilled. Strain into cocktail glass. garnish with a lemon twist.',
# 'image': metropolitan_image)
# DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': classical.id)
# DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': ballads.id)
# DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': compositional_ambient.id)
# DrinkIngredient.create('drink_id': metropolitan.id, 'ingredient_id': two_american_brandy.id)
# DrinkIngredient.create('drink_id': metropolitan.id, 'ingredient_id': one_vermouth.id)
# DrinkIngredient.create('drink_id': metropolitan.id, 'ingredient_id': two_angs.id)
# DrinkIngredient.create('drink_id': metropolitan.id, 'ingredient_id': demerara_syrup.id)
# DrinkTool.create('drink_id': metropolitan.id, 'tool_id': mixing_glass.id)
# DrinkTool.create('drink_id': metropolitan.id, 'tool_id': bar_spoon.id)
# DrinkTool.create('drink_id': metropolitan.id, 'tool_id': julep_strainer.id)

# margarita_image = File.open('app/assets/images/margarita.jpg')
# margarita = Drink.create('name': 'Margarita', 'directions': 'Combine ingredients in shaker. Add ice & shake. Strain into a salt rimmed rocks glass. Garnish with a lime wheel.',
# 'image': margarita_image)
# DrinkGenre.create('drink_id': margarita.id, 'genre_id': mexican_pop.id)
# DrinkGenre.create('drink_id': margarita.id, 'genre_id': spanish.id)
# DrinkGenre.create('drink_id': margarita.id, 'genre_id': mellow_gold.id)
# DrinkIngredient.create('drink_id': margarita.id, 'ingredient_id': casa_noble.id)
# DrinkIngredient.create('drink_id': margarita.id, 'ingredient_id': ofive_destillare.id)
# DrinkIngredient.create('drink_id': margarita.id, 'ingredient_id': lg_lime.id)
# DrinkIngredient.create('drink_id': margarita.id, 'ingredient_id': quarter_simple_syrup.id)
# DrinkTool.create('drink_id': margarita.id, 'tool_id': boston_shaker.id)
# DrinkTool.create('drink_id': margarita.id, 'tool_id': hawthorne_strainer.id)

# julep_image = File.open('app/assets/images/julep.jpg')
# julep = Drink.create('name': 'Julep', 'directions': 'Combine all ingredients in mixing glass. Muddle mint leaves. Strain liquid into glass, fill with crushed ice to heaping. Garnish with mint leaves.',
# 'image': julep_image)
# DrinkGenre.create('drink_id': julep.id, 'genre_id': americana.id)
# DrinkGenre.create('drink_id': julep.id, 'genre_id': folk.id)
# DrinkGenre.create('drink_id': julep.id, 'genre_id': country_road.id)
# DrinkGenre.create('drink_id': julep.id, 'genre_id': stomp_holler.id)
# DrinkGenre.create('drink_id': julep.id, 'genre_id': mellow_gold.id)
# DrinkIngredient.create('drink_id': julep.id, 'ingredient_id': two_american_brandy.id)
# DrinkIngredient.create('drink_id': julep.id, 'ingredient_id': half_simple_syrup.id)
# DrinkIngredient.create('drink_id': julep.id, 'ingredient_id': mint_leaves.id)
# DrinkTool.create('drink_id': julep.id, 'tool_id': mixing_glass.id)
# DrinkTool.create('drink_id': julep.id, 'tool_id': muddler.id)
# DrinkTool.create('drink_id': julep.id, 'tool_id': julep_strainer.id)
# DrinkTool.create('drink_id': julep.id, 'tool_id': lewis_bag.id)
# DrinkTool.create('drink_id': julep.id, 'tool_id': mallet.id)


# jack_rose_image = File.open('app/assets/images/jackRose.jpg')
# jack_rose = Drink.create('name': 'Jack Rose', 'directions': 'Pour ingredients into a mixing glass and fill with ice. Shake well with a Boston shaker. Strain into a chilled coupe, garnish with a twist of lemon.',
# 'image': jack_rose_image, 'tips': 'Heat 2 cups each fresh pomegranate juice and unbleached sugar with 2 oz. pomegranate molasses and 1 tsp. orange blossom water for simple, perfect homemade grenadine.')
# DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': rock_roll.id)
# DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': singer_songwriter.id)
# DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': classic_rock.id)
# DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': hard_rock.id)
# DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': drumline.id)
# DrinkIngredient.create('drink_id': jack_rose.id, 'ingredient_id': two_apple_brandy.id)
# DrinkIngredient.create('drink_id': jack_rose.id, 'ingredient_id': grenadine.id)
# DrinkIngredient.create('drink_id': jack_rose.id, 'ingredient_id': lg_lime.id)
# DrinkTool.create('drink_id': jack_rose.id, 'tool_id': boston_shaker.id)
# DrinkTool.create('drink_id': jack_rose.id, 'tool_id': hawthorne_strainer.id)

# horses_neck_image = File.open('app/assets/images/horsesNeck.jpg')
# horses_neck = Drink.create('name': 'Horses Neck', 'directions': 'Combine brandy and ginger beer in highball glass. Add ice. Garnish with generously long lemon peel. Add dash of bitters on top.',
# 'image': horses_neck_image, 'tips': 'A potato peeler or “y” peeler will work best to achieve the long lemon peel garnish.')
# DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': classical.id)
# DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': disco.id)
# DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': funk.id)
# DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': ska.id)
# DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': modern_rock.id)
# DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': garage_rock.id)
# DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': glam_metal.id)
# DrinkIngredient.create('drink_id': horses_neck.id, 'ingredient_id': onefive_american_brandy.id)
# DrinkIngredient.create('drink_id': horses_neck.id, 'ingredient_id': four_ginger_beer.id)
# DrinkIngredient.create('drink_id': horses_neck.id, 'ingredient_id': one_ang.id)
# DrinkIngredient.create('drink_id': horses_neck.id, 'ingredient_id': lemon.id)
# DrinkTool.create('drink_id': horses_neck.id, 'tool_id': peeler.id)
# DrinkTool.create('drink_id': horses_neck.id, 'tool_id': jigger.id)
# DrinkTool.create('drink_id': horses_neck.id, 'tool_id': highball_glass.id)

# harvard_image = File.open('app/assets/images/harvard.jpg')
# harvard = Drink.create('name': 'Harvard', 'directions': 'Combine brandy, vermouth and bitters in mixing glass. Fill with ice. Stir until well chilled. Strain into cocktail glass and top with cold club soda.',
# 'image': harvard_image)
# DrinkGenre.create('drink_id': harvard.id, 'genre_id': classic_rock.id)
# DrinkGenre.create('drink_id': harvard.id, 'genre_id': rock_roll.id)
# DrinkGenre.create('drink_id': harvard.id, 'genre_id': indie_rock.id)
# DrinkGenre.create('drink_id': harvard.id, 'genre_id': britpop.id)
# DrinkGenre.create('drink_id': harvard.id, 'genre_id': singer_songwriter.id)
# DrinkGenre.create('drink_id': harvard.id, 'genre_id': modern_rock.id)
# DrinkGenre.create('drink_id': harvard.id, 'genre_id': album_rock.id)
# DrinkIngredient.create('drink_id': harvard.id, 'ingredient_id': two_american_brandy.id)
# DrinkIngredient.create('drink_id': harvard.id, 'ingredient_id': one_vermouth.id)
# DrinkIngredient.create('drink_id': harvard.id, 'ingredient_id': club_soda.id)
# DrinkIngredient.create('drink_id': harvard.id, 'ingredient_id': two_angs.id)
# DrinkTool.create('drink_id': harvard.id, 'tool_id': mixing_glass.id)
# DrinkTool.create('drink_id': harvard.id, 'tool_id': bar_spoon.id)
# DrinkTool.create('drink_id': harvard.id, 'tool_id': julep_strainer.id)

# fish_house_punch_image = File.open('app/assets/images/fishHousePunch.jpg')
# fish_house_punch = Drink.create('name': 'Fish House Punch', 'directions': 'In a large bowl, add simple syrup and lemon peels, rub together to release the citrus oils into the sugar. Allow infusing for at least 30 minutes. Strain off the peels. Add brandy, rum, lemon juice and peach liqueur. Stir to mix. Add block of ice to chill. Allow thirty minutes for dilution. Garnish with lemon wheels and ladle into individual glasses. (serves 2-4)',
# 'image': fish_house_punch_image, 'tips': 'For easy frozen ice blocks at home, fill a 16 oz. plastic storage container with water and freeze overnight. Just before serving, remove the container from the freezer and leave upside-down for a couple minutes. The ice cube will slide right out.')
# DrinkGenre.create('drink_id': fish_house_punch.id, 'genre_id': house.id)
# DrinkGenre.create('drink_id': fish_house_punch.id, 'genre_id': progressive.id)
# DrinkGenre.create('drink_id': fish_house_punch.id, 'genre_id': british_blues.id)
# DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lg_american_brandy.id)
# DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lg_peach_liqueur.id)
# DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lg_jamaican_rum.id)
# DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': simple_syrup.id)
# DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lg_filtered_water.id)
# DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lemon_peels.id)
# DrinkTool.create('drink_id': fish_house_punch.id, 'tool_id': punch_bowl.id)
# DrinkTool.create('drink_id': fish_house_punch.id, 'tool_id': ladle.id)
#
# daisy_image = File.open('app/assets/images/daisy.jpg')
# daisy = Drink.create('name': 'Daisy', 'directions': 'Pour brandy, orange liqueur and lemon into a mixing glass and fill with ice. Shake well with a Boston shaker. Strain into chilled cocktail glass and top with two dashes of club soda.',
# 'image': daisy_image)
# DrinkGenre.create('drink_id': daisy.id, 'genre_id': country.id)
# DrinkGenre.create('drink_id': daisy.id, 'genre_id': folk.id)
# DrinkGenre.create('drink_id': daisy.id, 'genre_id': indie_folk.id)
# DrinkGenre.create('drink_id': daisy.id, 'genre_id': new_wave.id)
# DrinkGenre.create('drink_id': daisy.id, 'genre_id': neo_psychadelic.id)
# DrinkGenre.create('drink_id': daisy.id, 'genre_id': freak_folk.id)
# DrinkIngredient.create('drink_id': daisy.id, 'ingredient_id': two_american_brandy.id)
# DrinkIngredient.create('drink_id': daisy.id, 'ingredient_id': orange_liqueur75.id)
# DrinkIngredient.create('drink_id': daisy.id, 'ingredient_id': lg_lime.id)
# DrinkIngredient.create('drink_id': daisy.id, 'ingredient_id': club_soda.id)
# DrinkTool.create('drink_id': daisy.id, 'tool_id': boston_shaker.id)
# DrinkTool.create('drink_id': daisy.id, 'tool_id': hawthorne_strainer.id)
#
# chrysanthemum_image = File.open('app/assets/images/chrysanthemum.jpg')
# chrysanthemum = Drink.create('name': 'Chrysanthemum', 'directions': 'Shake with ice. Strain into cocktail glass. Squeeze orange peel on top.',
# 'image': chrysanthemum_image)
# DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': psychadelic_rock.id)
# DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': garage_rock.id)
# DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': chillwave.id)
# DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': freak_folk.id)
# DrinkIngredient.create('drink_id': chrysanthemum.id, 'ingredient_id': three_absinthe_blanche.id)
# DrinkIngredient.create('drink_id': chrysanthemum.id, 'ingredient_id': one_benedictine.id)
# DrinkIngredient.create('drink_id': chrysanthemum.id, 'ingredient_id': two_french_vermouth.id)
# DrinkIngredient.create('drink_id': chrysanthemum.id, 'ingredient_id': orange_peel.id)
# DrinkTool.create('drink_id': chrysanthemum.id, 'tool_id': boston_shaker.id)
# DrinkTool.create('drink_id': chrysanthemum.id, 'tool_id': hawthorne_strainer.id)

# corpse_reviver_image = File.open('app/assets/images/corpseReviver.jpg')
# corpse_reviver = Drink.create('name': 'Corpse Reviver', 'directions': 'Combine brandy, Apple brandy & sweet vermouth In Mixing glass. Stir with ice. Strain into a chilled cocktail glass.',
# 'image': corpse_reviver_image)
# DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': hardcore.id)
# DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': metalcore.id)
# DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': emo.id)
# DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': lofi.id)
# DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': neo_psychadelic.id)
# DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': garage_rock.id)
# DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': hard_rock.id)
# DrinkIngredient.create('drink_id': corpse_reviver.id, 'ingredient_id': one_american_brandy.id)
# DrinkIngredient.create('drink_id': corpse_reviver.id, 'ingredient_id': one_apple_brandy.id)
# DrinkIngredient.create('drink_id': corpse_reviver.id, 'ingredient_id': one_vermouth.id)
# DrinkTool.create('drink_id': corpse_reviver.id, 'tool_id': mixing_glass.id)
# DrinkTool.create('drink_id': corpse_reviver.id, 'tool_id': bar_spoon.id)
# DrinkTool.create('drink_id': corpse_reviver.id, 'tool_id': julep_strainer.id)
#
# old_fash_brandy_image = File.open('app/assets/images/oldFashBrandy.jpg')
# old_fash_brandy = Drink.create('name': 'Brandy Old Fashioned', 'directions': 'In a chilled rocks glass, muddle the sugar, bitters, orange wedge and cherry into a thick paste, careful not to work the orange peel. Add brandy, stir, and fill glass with ice and serve.',
# 'image': old_fash_brandy_image)
# DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': adult_standards.id)
# DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': crooner_jazz.id)
# DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': mellow_gold.id)
# DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': singer_songwriter.id)
# DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': album_rock.id)
# DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': modern_blues.id)
# DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': two_american_brandy.id)
# DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': sugar_cube.id)
# DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': two_angs.id)
# DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': thick_orange_wedge.id)
# DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': one_amarena.id)
# DrinkTool.create('drink_id': old_fash_brandy.id, 'tool_id': muddler.id)
# DrinkTool.create('drink_id': old_fash_brandy.id, 'tool_id': bar_spoon.id)
#
# ampersand_image = File.open('app/assets/images/ampersand.jpg')
# ampersand = Drink.create('name': 'Ampersand', 'directions': 'Combine ingredients in mixing glass. Add ice and stir. Strain into a cocktail glass. Top with dry curacao. Garnish with an expressed orange peel.',
# 'image': ampersand_image)
# DrinkGenre.create('drink_id': ampersand.id, 'genre_id': piano_rock.id)
# DrinkGenre.create('drink_id': ampersand.id, 'genre_id': improvisational_jazz.id)
# DrinkGenre.create('drink_id': ampersand.id, 'genre_id': post_bop.id)
# DrinkGenre.create('drink_id': ampersand.id, 'genre_id': acoustic_pop.id)
# DrinkGenre.create('drink_id': ampersand.id, 'genre_id': modern_rock.id)
# DrinkGenre.create('drink_id': ampersand.id, 'genre_id': album_rock.id)
# DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': one_american_brandy.id)
# DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': one_tom_gin.id)
# DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': one_vermouth.id)
# DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': bittermens.id)
# DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': destillare.id)
# DrinkTool.create('drink_id': ampersand.id, 'tool_id': mixing_glass.id)
# DrinkTool.create('drink_id': ampersand.id, 'tool_id': bar_spoon.id)
# DrinkTool.create('drink_id': ampersand.id, 'tool_id': hawthorne_strainer.id)
# DrinkTool.create('drink_id': ampersand.id, 'tool_id': jigger.id)
# DrinkTool.create('drink_id': ampersand.id, 'tool_id': citrus_peeler.id)
#
# crusta_image = File.open('app/assets/images/crusta.jpg')
# crusta = Drink.create('name': 'Crusta', 'directions': 'Pare the full peel off of the lemon and carefully curl the peel around the inside of the glass. Moisten the rim with cut lemon and dip in superfine sugar, forming a crust on the glass and peel. Combine ingredients in mixing glass. Add ice. Stir and strain into prepared glass.',
# 'image': crusta_image)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': blues.id)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': southern.id)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': traditional_jazz.id)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': jazz.id)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': classical.id)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': soul_blues.id)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': cajun.id)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': new_orleans_jazz.id)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': dixieland.id)
# DrinkGenre.create('drink_id': crusta.id, 'genre_id': ragtime.id)
# DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': two_american_brandy.id)
# DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': maraschino_liqueur.id)
# DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': lemon_juice.id)
# DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': demerara_syrup.id)
# DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': pehchauds_bitters.id)
# DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': crushed_ice.id)
# DrinkTool.create('drink_id': crusta.id, 'tool_id': mixing_glass.id)
# DrinkTool.create('drink_id': crusta.id, 'tool_id': bar_spoon.id)
# DrinkTool.create('drink_id': crusta.id, 'tool_id': hawthorne_strainer.id)
#
# almond_crusta_image = File.open('app/assets/images/almondCrusta.jpg')
# almond_crusta = Drink.create('name': 'Almond Blossom Crusta', 'directions': 'Prepare the cocktail glass by rubbing the orange wedge around the outside rim and dipping the rim in superfine sugar to form a crust approximately one inch deep. Add all of the ingredients to mixing glass. Fill with ice. Shake vigorously with Boston shaker. Strain into the sugar crusted cocktail glass. Garnish with orange twist.',
# 'tips': 'To achieve a proper rim on your cocktail, always begin with a non-chilled glass and coordinating citrus.',
# 'image': almond_crusta_image)
# DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': neo_soul.id)
# DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': indie_rock.id)
# DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': new_americana.id)
# DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': indie_anthem_folk.id)
# DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': bluegrass.id)
# DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': folk_punk.id)
# DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': gypsy_punk.id)
# DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': neo_psychadelic.id)
# DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': onefive_american_brandy.id)
# DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': lemon_juice75.id)
# DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': orgeat75.id)
# DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': superfine_whole.id)
# DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': orange_wedge_twist.id)
# DrinkTool.create('drink_id': almond_crusta.id, 'tool_id': boston_shaker.id)
# DrinkTool.create('drink_id': almond_crusta.id, 'tool_id': hawthorne_strainer.id)
#
# brandy_alexander_image = File.open('app/assets/images/brandyAlexander.jpg')
# brandy_alexander = Drink.create('name': 'Brandy Alexander', 'directions': 'Add all the ingredients to a mixing glass and fill with ice. Shake well with a Boston shaker and strain into a chilled coupe. Garnish with freshly grated nutmeg.',
# 'image': brandy_alexander_image)
# DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': r_b.id)
# DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': hip_hop.id)
# DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': rap.id)
# DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': smooth_jazz.id)
# DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': quiet_storm.id)
# DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': new_jack_swing.id)
# DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': focus.id)
# DrinkIngredient.create('drink_id': brandy_alexander.id, 'ingredient_id': two_american_brandy.id)
# DrinkIngredient.create('drink_id': brandy_alexander.id, 'ingredient_id': creme_cacao.id)
# DrinkIngredient.create('drink_id': brandy_alexander.id, 'ingredient_id': cream.id)
# DrinkIngredient.create('drink_id': brandy_alexander.id, 'ingredient_id': grated_nutmeg.id)
# DrinkTool.create('drink_id': brandy_alexander.id, 'tool_id': boston_shaker.id)
# DrinkTool.create('drink_id': brandy_alexander.id, 'tool_id': hawthorne_strainer.id)
# DrinkTool.create('drink_id': brandy_alexander.id, 'tool_id': zester.id)
#
# death_in_afternoon_image = File.open('app/assets/images/deathInAfternoon.jpg')
# death_in_afternoon = Drink.create('name': 'Death In The Afternoon', 'directions': '
#   Pour absinthe into a champagne flute and add cold brut champagne until it clouds up. Garnish with a lemon twist.',
# 'image': death_in_afternoon_image)
# DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': hard_stoner_rock.id)
# DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': spanish.id)
# DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': latin_rock.id)
# DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': cabaret.id)
# DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': metalcore.id)
# DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': psychadelic_rock.id)
# DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': glam_metal.id)
# DrinkIngredient.create('drink_id': death_in_afternoon.id, 'ingredient_id': absinthe_blanche_onefive.id)
# DrinkIngredient.create('drink_id': death_in_afternoon.id, 'ingredient_id': brut_champagne.id)
# DrinkIngredient.create('drink_id': death_in_afternoon.id, 'ingredient_id': lemon.id)
# DrinkTool.create('drink_id': death_in_afternoon.id, 'tool_id': jigger.id)
#
# absinthe_frappe_image = File.open('app/assets/images/absintheFrappe.jpg')
# absinthe_frappe = Drink.create('name': 'Absinthe Frappe', 'directions': 'Pour the absinthe, sugar, and the water into a blender. Blend for a moment to dissolve the sugar and then, with the blender running, add 3 or 4 ice cubes through the hole in the top, pausing between cubes to let them get crushed. Blend until smooth. Garnish with lemon/mint',
# 'image': absinthe_frappe_image)
# DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': metal.id)
# DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': black_metal.id)
# DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': death_metal.id)
# DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': trap_francais.id)
# DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': metalcore.id)
# DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': house.id)
# DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': techno.id)
# DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': mint.id)
# DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': lemon.id)
# DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': one_water.id)
# DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': superfine_sugar.id)
# DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': absinthe_blanche.id)
# DrinkTool.create('drink_id': absinthe_frappe.id, 'tool_id': blender.id)
#
# gt_image = File.open('app/assets/images/ginTonic.jpg')
# gin_and_tonic = Drink.create('name': 'Gin & Tonic', 'directions': 'Combine ingredients in an ice filled highball glass or wine goblet. Garnish with a lime, Juniper Berries, Grapefruit. Get creative with the garnish. Also try seasonal berries, cucumber or Rosemary',
# 'image': gt_image)
# DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': pop.id)
# DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': punk.id)
# DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': post_teen_pop.id)
# DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': viral_pop.id)
# DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': edm.id)
# DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': disco.id)
# DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': synth_pop.id)
# DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': deep_house.id)
# DrinkIngredient.create('drink_id': gin_and_tonic.id, 'ingredient_id': american_gin.id)
# DrinkIngredient.create('drink_id': gin_and_tonic.id, 'ingredient_id': four_tonic.id)
#
# rs_image = File.open('app/assets/images/redSangria.jpg')
# red_sangria = Drink.create('name': 'Red Sangria', 'directions': 'Combine brandy & honey in a large pitcher and stir until honey is dissolved. Add fruit and mash gently with the back of a wooden spoon to release juices. Add wine and stir. Cover and refrigerate for at least 8 hours and up to 48 hours. Top with soda & mint. Serve in ice-filled glasses.','image': rs_image)
# DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': salsa.id)
# DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': folk.id)
# DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': regional_mexican.id)
# DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': latin.id)
# DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': latin_pop.id)
# DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': spanish_pop.id)
# DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': grupera.id)
# DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': red_table_wine.id)
# DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': sprig_mint.id)
# DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': two_mixed_berry.id)
# DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': grapefruit.id)
# DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': quarter_honey.id)
# DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': lemon_sliced.id)
# DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': american_brandy.id)
