# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
DrinkTool.destroy_all
DrinkIngredient.destroy_all
DrinkGenre.destroy_all

Genre.destroy_all

tracestep = Genre.create('name': 'tracestep')
electronic = Genre.create('name': 'electronic')
canadian = Genre.create('name': 'canadian')
post_grunge = Genre.create('name': 'post-grunge')
gangster_rap = Genre.create('name': 'gangster rap')
swedish_pop = Genre.create('name': 'swedish pop')
dance_pop = Genre.create('name': 'dance pop')
redneck = Genre.create('name': 'redneck')
swedish = Genre.create('name': 'swedish')
bollywood = Genre.create('name': 'bollywood')
retro_electro = Genre.create('name': 'retro electro')
uk_hip_hop = Genre.create('name': 'uk hip hop')
west_coast_rap = Genre.create('name': 'west coast rap')
mexican = Genre.create('name': 'mexican')
texas_country = Genre.create('name': 'texas country')
outlaw_country = Genre.create('name': 'outlaw country')
filter_house = Genre.create('name': 'filter house')
rock_espanol = Genre.create('name': 'rock en espanol')
roots_rock = Genre.create('name': 'roots rock')
new_age = Genre.create('name': 'new age')
grime = Genre.create('name': 'grime')
funk = Genre.create('name': 'funk')
canadian_rock = Genre.create('name': 'canadian rock')
classify = Genre.create('name': 'classify')
soul = Genre.create('name': 'soul')
chanson = Genre.create('name': 'chanson')
mexican_indie = Genre.create('name': 'mexican indie')
progressive_metal = Genre.create('name': 'progressive metal')
irish_metal = Genre.create('name': 'irish metal')
melodic_hardcore = Genre.create('name': 'melodic hardcore')
permanent_wave = Genre.create('name': 'permanent wave')
pop_rap = Genre.create('name': 'pop rap')
broadway = Genre.create('name': 'broadway')
europop = Genre.create('name': 'europop')
exotica = Genre.create('name': 'exotica')
show_tunes = Genre.create('name': 'show tunes')
mandopop = Genre.create('name': 'mandopop')
celtic = Genre.create('name': 'celtic')
alternative_dance = Genre.create('name': 'alternative dance')
alternative_country = Genre.create('name': 'alternative country')
comic = Genre.create('name': 'comic')
neoclassical_metal = Genre.create('name': 'neo classical metal')
free_jazz = Genre.create('name': 'free jazz')
comedy_rock = Genre.create('name': 'comedy rock')
pop_rock = Genre.create('name': 'pop_rock')
bay_hip_hop = Genre.create('name': 'bay area hip hop')
free_improvisation = Genre.create('name': 'free improvisation')
skate_punk = Genre.create('name': 'skate punk')
dark_wave = Genre.create('name': 'dark wave')
hollywood = Genre.create('name': 'hollywood')
new_wave_pop = Genre.create('name': 'new wave pop')
traditional_country = Genre.create('name': 'traditional country')
easy_listening = Genre.create('name': 'easy listening')
catstep = Genre.create('name': 'catstep')
neoclassical = Genre.create('name': 'neoclassical')
soundtrack = Genre.create('name': 'soundtrack')
new_rave = Genre.create('name': 'new rave')
neo_mellow = Genre.create('name': 'neo mellow')
deep_chiptune = Genre.create('name': 'deep chiptune')
stomp_whittle = Genre.create('name': 'stomp and whittle')
pop_emo = Genre.create('name': 'pop emo')
laboratorio = Genre.create('name': 'laboratorio')
experimental = Genre.create('name': 'experimental')
pixie = Genre.create('name': 'pixie')
screamo = Genre.create('name': 'screamo')
lounge = Genre.create('name': 'lounge')
cello = Genre.create('name': 'cello')
gospel = Genre.create('name': 'gospel')
metropopolis = Genre.create('name': 'metropopolis')
complextro = Genre.create('name': 'complextro')
alternative_rock = Genre.create('name': 'alternative rock')
alternative_metal = Genre.create('name': 'alternative metal')
remix = Genre.create('name': 'remix')
british = Genre.create('name': 'british')
spanish_pop = Genre.create('name': 'spanish pop')
neo_psychadelic = Genre.create('name': 'neo-psychadelic')
psychadelic_rock = Genre.create('name': 'psychadelic rock')
glam_metal = Genre.create('name': 'glam metal')
latin_pop = Genre.create('name': 'latin pop')
grupera = Genre.create('name': 'grupera')
pop = Genre.create('name': 'pop')
focus = Genre.create('name': 'focus')
synth_pop = Genre.create('name': 'synthpop')
deep_house = Genre.create('name': 'deep house')
emo = Genre.create('name': 'emo')
punk = Genre.create('name': 'punk')
hardcore = Genre.create('name': 'hardcore')
rock = Genre.create('name': 'rock')
metal = Genre.create('name': 'metal')
rap = Genre.create('name': 'rap')
post_teen_pop = Genre.create('name': 'post-teen pop')
viral_pop = Genre.create('name': 'viral pop')
edm = Genre.create('name': 'edm')
disco = Genre.create('name': 'disco')
house = Genre.create('name': 'house')
techno = Genre.create('name': 'techno')
salsa = Genre.create('name': 'salsa')
folk = Genre.create('name': 'folk')
regional_mexican = Genre.create('name': 'regional mexican')
latin = Genre.create('name': 'Latin')
black_metal = Genre.create('name': 'black metal')
death_metal = Genre.create('name': 'death metal')
trap_francais = Genre.create('name': 'trap francais')
metalcore = Genre.create('name': 'metalcore')
hard_stoner_rock = Genre.create('name': 'hard stoner rock')
spanish = Genre.create('name': 'spanish')
latin_rock = Genre.create('name': 'latin rock')
cabaret = Genre.create('name': 'cabaret')
r_b = Genre.create('name': 'R&B')
hip_hop = Genre.create('name': 'hip hop')
smooth_jazz = Genre.create('name': 'smooth jazz')
quiet_storm = Genre.create('name': 'quiet storm')
blues = Genre.create('name': 'blues')
soul_blues = Genre.create('name': 'soul blues')
southern = Genre.create('name': 'southern')
traditional_jazz = Genre.create('name': 'traditional jazz')
jazz = Genre.create('name': 'jazz')
classical = Genre.create('name': 'classical')
cajun = Genre.create('name': 'cajun')
new_orleans_jazz = Genre.create('name': 'new orleans jazz')
ragtime = Genre.create('name': 'ragtime')
dixieland = Genre.create('name': 'dixieland')
new_jack_swing = Genre.create('name': 'new jack swing')
neo_soul = Genre.create('name': 'neo soul')
indie_rock = Genre.create('name': 'indie rock')
new_americana = Genre.create('name': 'new americana')
americana = Genre.create('name': 'americana')
indie_anthem_folk = Genre.create('name': 'indie anthem folk')
folk_punk = Genre.create('name': 'folk punk')
gypsy_punk = Genre.create('name': 'gypsy punk')
bluegrass = Genre.create('name': 'bluegrass')
piano_rock = Genre.create('name': 'piano rock')
improvisational_jazz = Genre.create('name': 'improvisational jazz')
post_bop = Genre.create('name': 'post bop')
adult_standards = Genre.create('name': 'adult standards')
crooner_jazz = Genre.create('name': 'crooner jazz')
acoustic_pop = Genre.create('name': 'acoustic pop')
modern_rock = Genre.create('name': 'modern rock')
album_rock = Genre.create('name': 'album rock')
mellow_gold = Genre.create('name': 'mellow gold')
singer_songwriter = Genre.create('name': 'singer-songwriter')
modern_blues = Genre.create('name': 'modern blues')
lofi = Genre.create('name': 'lo-fi')
garage_rock = Genre.create('name': 'garage rock')
hard_rock = Genre.create('name': 'hard rock')
chillwave = Genre.create('name': 'chillwave')
freak_folk = Genre.create('name': 'freak folk')
country = Genre.create('name': 'country')
indie_folk = Genre.create('name': 'indie folk')
new_wave = Genre.create('name': 'new wave')
progressive = Genre.create('name': 'progressive')
british_blues = Genre.create('name': 'british blues')
rock_roll = Genre.create('name': 'rock-and-roll')
classic_rock = Genre.create('name': 'classic rock')
britpop = Genre.create('name': 'britpop')
ska = Genre.create('name': 'ska')
funk = Genre.create('name': 'funk')
drumline = Genre.create('name': 'drumline')
country_road = Genre.create('name': 'country road')
stomp_holler = Genre.create('name': 'stomp and holler')
mexican_pop = Genre.create('name': 'mexican pop')
compositional_ambient = Genre.create('name': 'compositional ambient')
ballads = Genre.create('name': 'ballads')
vintage_jazz = Genre.create('name': 'vintage jazz')
southern_soul = Genre.create('name': 'southern soul')
french = Genre.create('name': 'french')
acoustic_pop = Genre.create('name': 'acoustic pop')
indie_rb = Genre.create('name': 'indie r&b')
gypsy_folk = Genre.create('name': 'gypsy folk')
greek = Genre.create('name': 'greek')
rebetika = Genre.create('name': 'rebetika')
motown = Genre.create('name': 'MoTown')
art_pop = Genre.create('name': 'art pop')
christian_music = Genre.create('name': 'christian music')
jazz_blues = Genre.create('name': 'jazz blues')
underground_hip_hop = Genre.create('name': 'underground hip hop')
dirty_south_hip_hop = Genre.create('name': 'dirth south hip hop')
french_hip_hop = Genre.create('name': 'french hip hop')
southern_hip_hop = Genre.create('name': 'southern hip hop')
trap_music = Genre.create('name': 'trap music')
tropical = Genre.create('name': 'tropical')
japanese_city_pop = Genre.create('name': 'japanese city pop')
k_hop = Genre.create('name': 'k-hop')
j_poprock = Genre.create('name': 'k-hop')
malaysian_hip_hop = Genre.create('name': 'malaysian hip hop')
thai_hip_hop = Genre.create('name': 'thai hip hop')
malaysian = Genre.create('name': 'malaysian')
oriental_groove = Genre.create('name': 'oriental groove')
nineteen_eighties = Genre.create('name': '1980s')
indian_classical = Genre.create('name': 'indian classical')
sitar = Genre.create('name': 'sitar')
modern_country_rock = Genre.create('name': 'modern country rock')
southern_rock = Genre.create('name': 'southern rock')
francais = Genre.create('name': 'francais')
synth = Genre.create('name': 'synth')
shoegaze = Genre.create('name': 'shoegaze')
british_pop = Genre.create('name': 'british pop')
chicago_soul = Genre.create('name': 'chicago soul')
chicago_hip_hop = Genre.create('name': 'chicago hip hop')
alt_90s = Genre.create('name': '90s Alternative')
beach_music = Genre.create('name': 'beach music')
ukulele = Genre.create('name': 'ukulele')
latin_alternative = Genre.create('name': 'latin alternative')
reggaeton = Genre.create('name': 'reggaeton')
reggae = Genre.create('name': 'reggae')
reggae_fusion = Genre.create('name': 'reggae fusion')
caribbean = Genre.create('name': 'caribbean')
tropical_house = Genre.create('name': 'tropical house')
dirty_south_rap = Genre.create('name': 'dirty south rap')
brostep = Genre.create('name': 'brostep')
scottish = Genre.create('name': 'scottish')


Artist.destroy_all

Tool.destroy_all

blender = Tool.create('name': 'Blender')
strainer = Tool.create('name': 'Strainer')
bar_spoon = Tool.create('name': 'Bar Spoon')
boston_shaker = Tool.create('name': 'Boston Shaker')
hawthorne_strainer = Tool.create('name': 'Hawthorne Strainer')
zester = Tool.create('name': 'Zester/Grater')
jigger = Tool.create('name': 'Jigger')
mixing_glass = Tool.create('name': 'Mixing Glass')
citrus_peeler = Tool.create('name': 'Citrus Peeler')
glass_rimmer = Tool.create('name': 'Glass Rimmer')
fruit_pick = Tool.create('name': 'Fruit Pick')
muddler = Tool.create('name': 'Muddler')
pint_glass = Tool.create('name': 'Pint Glass')
julep_strainer = Tool.create('name': 'Julep Strainer')
punch_bowl = Tool.create('name': 'Punch bowl')
ladle = Tool.create('name': 'Ladle')
highball_glass = Tool.create('name': 'Highball glass')
peeler = Tool.create('name': 'Peeler')
lewis_bag = Tool.create('name': 'Lewis bag')
mallet = Tool.create('name': 'Mallet')
straw = Tool.create('name': 'Straw')
shaker_tins = Tool.create('name': 'Shaker Tins')
collins_glass = Tool.create('name': 'Collins Glass')
glass = Tool.create('name': 'Glass')
pitcher = Tool.create('name': 'Pitcher')
knife = Tool.create('name': 'Knife')
strainer = Tool.create('name': 'Strainer')
saucepan = Tool.create('name': 'Saucepan')
large_bowl = Tool.create('name': 'Large bowl')
jelly_bag = Tool.create('name': 'Jelly bag')


Ingredient.destroy_all

spice_base = 'Spice Base'
horseradish = 'Ground Horseradish'
tomato_juice = 'Tomato Juice'
apple_brandy = 'Copper & Kings Un-Aged Apple Brandy'

immature_brandy = 'Immature Brandy'
lime_juice = 'Freshly squeezed lime juice'
angostura_bitters = 'angostura bitters'


club_soda = Ingredient.create('name': 'Club Soda')
two_club_soda = Ingredient.create('name': 'Club Soda', 'amount': 2)
tonic = Ingredient.create('name': 'Tonic')
lime = Ingredient.create('name': 'Lime')
mint = Ingredient.create('name': 'Mint')
lemon = Ingredient.create('name': 'Lemon')
celery = Ingredient.create('name': 'Celery')
olives = Ingredient.create('name': 'Olives')
peppers = Ingredient.create('name': 'Peppers')
citrus = Ingredient.create('name': 'Citrus')
meat = Ingredient.create('name': 'Meat')
two_apple_brandy = Ingredient.create('name': apple_brandy, 'amount': 2, 'unit': 'oz')
four_tomato_juice = Ingredient.create('name': tomato_juice, 'amount': 4, 'unit': 'oz')
one_spice_base = Ingredient.create('name': spice_base, 'amount': 1, 'unit': 'oz')
one_horseradish = Ingredient.create('name': horseradish, 'amount': 1, 'unit': 'tsp')
ginger_ale = Ingredient.create('name': 'Ginger Ale')
two_immature = Ingredient.create('name': immature_brandy, 'amount': 2, 'unit': 'oz')
sm_lime = Ingredient.create('name': lime_juice, 'amount': 0.25, 'unit': 'oz')
three_angs = Ingredient.create('name': angostura_bitters, 'amount': 3, 'unit': 'drops')
red_table_wine = Ingredient.create('name': 'Red table win', 'amount': 750, 'unit': 'ML')
sprig_mint = Ingredient.create('name': 'Sprig of mint')
two_mixed_berry = Ingredient.create('name': 'Mixed Berries', 'amount': 2, 'unit': 'cups')
grapefruit = Ingredient.create('name': 'Grapefruit, sliced', 'amount': 1)
lemon_sliced = Ingredient.create('name': 'Lemon, thinly sliced', 'amount': 1)
quarter_honey = Ingredient.create('name': 'Honey', 'amount': 0.25, 'unit': 'cup')
american_brandy = Ingredient.create('name': 'American craft brandy', 'amount': 0.25, 'unit': 'cup')
absinthe_blanche = Ingredient.create('name': 'Copper & Kings Absinthe Blanche', 'amount': 1, 'unit': 'oz')
superfine_sugar = Ingredient.create('name': 'Superfine Sugar', 'amount': 0.5, 'unit': 'tsp')
one_water = Ingredient.create('name': 'Water', 'amount': 1, 'unit': 'oz')
absinthe_blanche_onefive = Ingredient.create('name': 'Copper & Kings Absinthe Blanche', 'amount': 1.5, 'unit': 'oz')
brut_champagne = Ingredient.create('name': 'Brut Champagne', 'amount': 4, 'unit': 'oz')
american_gin = Ingredient.create('name': 'American Dry Gin', 'amount': 2, 'unit': 'oz')
four_tonic = Ingredient.create('name': 'Tonic Water', 'amount': 4, 'unit': 'oz')
two_american_brandy = Ingredient.create('name': 'Copper & Kings American Craft Brandy', 'amount': 2, 'unit': 'oz')
creme_cacao = Ingredient.create('name': 'Crème de Cacao', 'amount': 0.75, 'unit': 'oz')
cream = Ingredient.create('name': 'Cream', 'amount': 0.75, 'unit': 'oz')
grated_nutmeg = Ingredient.create('name': 'Freshly grated nutmeg')
maraschino_liqueur = Ingredient.create('name': 'Maraschino liqueur (Luxardo)', 'amount': 1, 'unit': 'tsp')
lemon_juice = Ingredient.create('name': 'Fresh lemon juice', 'amount': 0.5, 'unit': 'tsp')
demerara_syrup = Ingredient.create('name': 'Bar spoon of demerara syrup (we use 2:1)')
pehchauds_bitters = Ingredient.create('name': 'peychaud’s bitters', 'amount': 2, 'unit': 'dashes')
crushed_ice = Ingredient.create('name': 'Crushed Ice')
onefive_american_brandy = Ingredient.create('name': 'Copper & Kings American Craft Brandy', 'amount': 1.5, 'unit': 'oz')
half_gin = Ingredient.create('name': 'Gin', 'amount': 0.5, 'unit': 'oz')
lemon_juice75 = Ingredient.create('name': 'Freshly squeezed lemon juice', 'amount': 0.75, 'unit': 'oz')
orgeat75 = Ingredient.create('name': 'Orgeat', 'amount': 0.75, 'unit': 'oz')
superfine_whole = Ingredient.create('name': 'Superfine sugar')
orange_wedge_twist = Ingredient.create('name': 'Large orange wedge and twist')
one_american_brandy = Ingredient.create('name': 'Copper & Kings American Brandy', 'amount': 1, 'unit': 'oz')
one_tom_gin = Ingredient.create('name': 'Copper & Kings American Old Tom Gin', 'amount': 1, 'unit': 'oz')
one_vermouth = Ingredient.create('name': 'Sweet Vermouth', 'amount': 1, 'unit': 'oz')
bittermens = Ingredient.create('name': 'Bittermens Amere Sauvage (Or, Substitute: 2 Dashes Orange Bitters)', 'amount': 0.25, 'unit': 'oz')
destillare = Ingredient.create('name': 'Destillaré Orange Curaçao To Top')
sugar_cube = Ingredient.create('name': 'Sugar cube', 'amount': 1)
two_angs = Ingredient.create('name': 'Angotsura bitters', 'amount': 2, 'unit': 'dashes')
thick_orange_wedge = Ingredient.create('name': 'Thick slice orange wedge', 'amount': 1)
one_amarena = Ingredient.create('name': 'Amarena/Maraska Cherry', 'amount': 1)
one_apple_brandy = Ingredient.create('name': apple_brandy, 'amount': 1, 'unit': 'oz')
three_absinthe_blanche = Ingredient.create('name': 'Copper & Kings Absinthe Blanche', 'amount': 3, 'unit': 'dashes')
one_benedictine = Ingredient.create('name': 'Bénédictine', 'amount': 1, 'unit': 'oz')
two_french_vermouth = Ingredient.create('name': 'French vermouth', 'amount': 2, 'unit': 'oz')
orange_peel = Ingredient.create('name': 'Orange Peel')
orange_liqueur75 = Ingredient.create('name': 'Orange liqueur (dry curacao or Cointreau)', 'amount': 0.75, 'unit': 'oz')
lg_lime = Ingredient.create('name': lime_juice, 'amount': 0.75, 'unit': 'oz')
lg_american_brandy = Ingredient.create('name': 'Copper & Kings American Craft Brandy', 'amount': 8, 'unit': 'oz')
lg_peach_liqueur = Ingredient.create('name': 'Peach liqueur (Mathilde, Rothman & Winter)', 'amount': 4, 'unit': 'oz')
lg_jamaican_rum = Ingredient.create('name': 'Jamaican rum (Blackwell, Appleton, Smith & Cross)', 'amount': 4, 'unit': 'oz')
xlg_lime = Ingredient.create('name': lime_juice, 'amount': 6, 'unit': 'oz')
simple_syrup = Ingredient.create('name': '1:1 simple syrup', 'amount': 4, 'unit': 'oz')
lg_filtered_water = Ingredient.create('name': 'Filtered water frozen into large ice block', 'amount': 16, 'unit': 'oz')
lemon_peels = Ingredient.create('name': 'Lemon Peels')
four_ginger_beer = Ingredient.create('name': 'Ginger Beer', 'amount': 4, 'unit': 'oz')
one_ang = Ingredient.create('name': 'Angotsura bitters', 'amount': 1, 'unit': 'dash')
grenadine = Ingredient.create('name': 'Grenadine', 'amount': 0.75, 'unit': 'oz')
half_simple_syrup = Ingredient.create('name': 'Simple Syrup', 'amount': 0.5, 'unit': 'oz')
mint_leaves = Ingredient.create('name': '8-10 Mint Leaves')
casa_noble = Ingredient.create('name': 'Casa Noble Blanco Tequila', 'amount': 2, 'unit': 'oz')
ofive_destillare = Ingredient.create('name': 'Destillaré Intense Orange Curaçao', 'amount': 0.5, 'unit': 'oz')
quarter_simple_syrup = Ingredient.create('name': 'Simple Syrup', 'amount': 0.25, 'unit': 'oz')
med_lime = Ingredient.create('name': lime_juice, 'amount': 0.5, 'unit': 'oz')
lime_wedge = Ingredient.create('name': 'Lime wedge, garnish')
three_peychauds_bitters = Ingredient.create('name': 'Peychaud’s bitters', 'amount': 3, 'unit': 'dashes')
demerara_cube = Ingredient.create('name': 'Demerara Sugar Cube', 'amount': 1)
absinthe_rinse = Ingredient.create('name': 'Absinthe Rinse')
lemon_twist = Ingredient.create('name': 'Lemon Twist')
one_lime = Ingredient.create('name': lime_juice, 'amount': 1, 'unit': 'oz')
lime_wheel = Ingredient.create('name': 'Lime Wheel')
lemon_wheel = Ingredient.create('name': 'Lemon Wheel')
half_egg = Ingredient.create('name': 'Fresh egg white', 'amount': 0.5, 'unit': 'oz')
one_simple_syrup = Ingredient.create('name': '2:1 simple syrup', 'amount': 1, 'unit': 'oz')
one_lemon_juice = Ingredient.create('name': 'Fresh lemon juice', 'amount': 1, 'unit': 'oz')
ice_water = Ingredient.create('name': 'Ice cold water')
one_high_west = Ingredient.create('name': 'High West Double Rye Whiskey', 'amount': 1, 'unit': 'oz')
half_benedictine = Ingredient.create('name': 'Benedictine', 'amount': 0.5, 'unit': 'oz')
twist_orange = Ingredient.create('name': 'Twist of Orange')
brandied_cherry = Ingredient.create('name': 'Brandied Cherry')
two_orange_bitters = Ingredient.create('name': 'Orange Bitters', 'amount': 2, 'unit': 'dashes')
one_orgeat = Ingredient.create('name': 'Orgeat Syrup', 'amount': 1, 'unit': 'tbsp')
four_angs = Ingredient.create('name': 'Angotsura Bitters', 'amount': 4, 'unit': 'dashes')
onefive_american_gin = Ingredient.create('name': 'Copper & Kings American Dry Gin', 'amount': 1.5, 'unit': 'oz')
one_orange_juice = Ingredient.create('name': 'Orange Juice', 'amount': 1, 'unit': 'oz')
quarter_benedictine = Ingredient.create('name': 'Benedictine', 'amount': 0.25, 'unit': 'oz')
drizzle_cherry = Ingredient.create('name': 'Drizzle of Cherry Brandy Or Cherry Heering')
soda_water = Ingredient.create('name': 'Soda Water')
twofive_american_brandy = Ingredient.create('name': 'Copper & Kings American Craft Brandy', 'amount': 2.5, 'unit': 'oz')
one_curacao = Ingredient.create('name': 'Curaçao ', 'amount': 1, 'unit': 'tsp')
one_pineapple = Ingredient.create('name': 'Pineapple syrup ', 'amount': 1, 'unit': 'tsp')
two_bokers = Ingredient.create('name': '2 or 3 dashes of bitters (Boker’s genuine)', 'amount': 1, 'unit': 'tsp')
two_maraschino = Ingredient.create('name': 'Maraschino', 'amount': 2, 'unit': 'dashes')
onefive_vermouth = Ingredient.create('name': 'French Vermouth', 'amount': 1.5, 'unit': 'oz')
two_anisette = Ingredient.create('name': 'Anisette', 'amount': 2, 'unit': 'dashes')
one_destillare = Ingredient.create('name': 'Destillaré Orange Curaçao', 'amount': 1, 'unit': 'oz')
champagne = Ingredient.create('name': 'Champagne')
powdered_sugar = Ingredient.create('name': 'One bar spoon full of powered sugar')
maraschino_liqueur75 = Ingredient.create('name': 'Maraschino Liqueur', 'amount': 0.75, 'unit': 'oz')
creme_violette = Ingredient.create('name': 'Crème de violette or Crème Yvette', 'amount': 0.25, 'unit': 'oz')
roses_lime75 = Ingredient.create('name': "Rose's lime juice", 'amount': 0.75, 'unit': 'oz')
simple_syrup75 = Ingredient.create('name': "Simple Syrup", 'amount': 0.75, 'unit': 'oz')
fresh_mint = Ingredient.create('name': "Fresh Mint Leaf", 'amount': 1)
falernum25 = Ingredient.create('name': "Falernum", 'amount': 0.25, 'unit': 'oz')
half_orgeat = Ingredient.create('name': "Orgeat", 'amount': 0.50, 'unit': 'oz')
half_passionfruit = Ingredient.create('name': "Passionfruit syrup", 'amount': 0.5, 'unit': 'oz')
half_aged_rum = Ingredient.create('name': "Aged rum", 'amount': 0.5, 'unit': 'oz')
one_gin = Ingredient.create('name': "Copper & Kings American Dry Gin", 'amount': 1, 'unit': 'oz')
ginger_beer = Ingredient.create('name': "Ginger beer")
egg = Ingredient.create('name': "1 Egg")
one_port_wine = Ingredient.create('name': "Port wine", 'amount': 1, 'unit': 'oz')
half_brandy = Ingredient.create('name': "Copper & Kings American Craft Brandy", 'amount': 0.5, 'unit': 'oz')
two_craftwerk = Ingredient.create('name': "Sierra Nevada Chocolate Cherry Stout Brandy", 'amount': 2, 'unit': 'oz')
dolin_rouge = Ingredient.create('name': "Dolin Rouge", 'amount': 0.75, 'unit': 'oz')
luxardo = Ingredient.create('name': "Luxardo maraschino cherry liquer", 'amount': 0.25, 'unit': 'oz')
six_brandy = Ingredient.create('name': "Copper & Kings American Craft Brandy ", 'amount': 6, 'unit': 'cup')
el_lemons = Ingredient.create('name': "Lemons", 'amount': 11)
two_lemon_juice = Ingredient.create('name': "Lemon Juice", 'amount': 2, 'unit': 'cups')
four_spring = Ingredient.create('name': "Spring Water", 'amount': 4, 'unit': 'cups')
halflb_sugar = Ingredient.create('name': "Sugar", 'amount': 0.5, 'unit': 'lb')
three_milk = Ingredient.create('name': "Whole Milk", 'amount': 3, 'unit': 'cups')
one_campari = Ingredient.create('name': "Campari", 'amount': 1, 'unit': 'oz')
one_dolin_rouge = Ingredient.create('name': "Dolin Rouge", 'amount': 1, 'unit': 'oz')
two_american_gin = Ingredient.create('name': "Copper & Kings American Dry Gin", 'amount': 2, 'unit': 'oz')
fave_coffee = Ingredient.create('name': "Your Favorite Coffee")


Drink.destroy_all

irish_coffee_image = File.open('app/assets/images/irishCoffee.jpg')
irish_coffee = Drink.create('name': 'Irish Coffee', 'directions': 'Add American brandy to mug, top with warm coffee and whipped cream.',
'image': irish_coffee_image)
DrinkGenre.create('drink_id': irish_coffee.id, 'genre_id': celtic.id)
DrinkGenre.create('drink_id': irish_coffee.id, 'genre_id': irish_metal.id)
DrinkGenre.create('drink_id': irish_coffee.id, 'genre_id': hollywood.id)
DrinkGenre.create('drink_id': irish_coffee.id, 'genre_id': melodic_hardcore.id)
DrinkGenre.create('drink_id': irish_coffee.id, 'genre_id': grime.id)
DrinkIngredient.create('drink_id': irish_coffee.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': irish_coffee.id, 'ingredient_id': fave_coffee.id)

gin_martini_image = File.open('app/assets/images/ginMartini.jpg')
gin_martini = Drink.create('name': 'Gin Martini', 'directions': 'Stir ingredients briskly with ice, then strain into a chilled glass. Twist a small strip of lemon peel over the drink. You may drop it in, if you prefer.',
'image': gin_martini_image)
DrinkGenre.create('drink_id': gin_martini.id, 'genre_id': free_improvisation.id)
DrinkGenre.create('drink_id': gin_martini.id, 'genre_id': soundtrack.id)
DrinkGenre.create('drink_id': gin_martini.id, 'genre_id': classical.id)
DrinkIngredient.create('drink_id': gin_martini.id, 'ingredient_id': two_american_gin.id)
DrinkIngredient.create('drink_id': gin_martini.id, 'ingredient_id': one_vermouth.id)
DrinkIngredient.create('drink_id': gin_martini.id, 'ingredient_id': two_orange_bitters.id)
DrinkTool.create('drink_id': gin_martini.id, 'tool_id': julep_strainer.id)
DrinkTool.create('drink_id': gin_martini.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': gin_martini.id, 'tool_id': mixing_glass.id)

negroni_image = File.open('app/assets/images/negroni.jpg')
negroni = Drink.create('name': 'Sea of Clouds (negroni)', 'directions': 'Add Ingredients To Mixing Glass. Fill With Ice. Stir And Strain Into A Coupe. Garnish With Orange Peel Or Lemon Twist.',
'image': negroni_image)
DrinkGenre.create('drink_id': negroni.id, 'genre_id': laboratorio.id)
DrinkGenre.create('drink_id': negroni.id, 'genre_id': permanent_wave.id)
DrinkGenre.create('drink_id': negroni.id, 'genre_id': rock.id)
DrinkGenre.create('drink_id': negroni.id, 'genre_id': deep_chiptune.id)
DrinkIngredient.create('drink_id': negroni.id, 'ingredient_id': one_american_brandy.id)
DrinkIngredient.create('drink_id': negroni.id, 'ingredient_id': one_campari.id)
DrinkIngredient.create('drink_id': negroni.id, 'ingredient_id': one_dolin_rouge.id)
DrinkTool.create('drink_id': negroni.id, 'tool_id': julep_strainer.id)
DrinkTool.create('drink_id': negroni.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': negroni.id, 'tool_id': mixing_glass.id)

milk_punch_image = File.open('app/assets/images/milkPunch.jpg')
milk_punch = Drink.create('name': 'Milk Punch', 'directions': 'Zest 11 lemons. Squeeze 2 cups of lemon juice and put aside. Steep the lemon zest in the brandy for 24 hours. Strain out the lemon zest. Add 4 cups spring water, 1 freshly grated nutmeg, 2 cups lemon juice and 1 ⅛ cups of sugar to the brandy. Stir until the sugar dissolves. Bring 3 cups whole milk to a boil. As soon as the milk boils, add the hot milk to the brandy and stir. The heat, lemon juice and alcohol will begin to curdle the milk. Let the punch stand for 2 hours.Strain the punch through a jelly bag (or pillow case) until clear. Serve cold.',
'image': milk_punch_image)
DrinkGenre.create('drink_id': milk_punch.id, 'genre_id': reggaeton.id)
DrinkGenre.create('drink_id': milk_punch.id, 'genre_id': scottish.id)
DrinkGenre.create('drink_id': milk_punch.id, 'genre_id': celtic.id)
DrinkGenre.create('drink_id': milk_punch.id, 'genre_id': bay_hip_hop.id)
DrinkGenre.create('drink_id': milk_punch.id, 'genre_id': rap.id)
DrinkGenre.create('drink_id': milk_punch.id, 'genre_id': uk_hip_hop.id)
DrinkGenre.create('drink_id': milk_punch.id, 'genre_id': west_coast_rap.id)
DrinkIngredient.create('drink_id': milk_punch.id, 'ingredient_id': six_brandy.id)
DrinkIngredient.create('drink_id': milk_punch.id, 'ingredient_id': el_lemons.id)
DrinkIngredient.create('drink_id': milk_punch.id, 'ingredient_id': two_lemon_juice.id)
DrinkIngredient.create('drink_id': milk_punch.id, 'ingredient_id': four_spring.id)
DrinkIngredient.create('drink_id': milk_punch.id, 'ingredient_id': grated_nutmeg.id)
DrinkIngredient.create('drink_id': milk_punch.id, 'ingredient_id': halflb_sugar.id)
DrinkIngredient.create('drink_id': milk_punch.id, 'ingredient_id': three_milk.id)
DrinkTool.create('drink_id': milk_punch.id, 'tool_id': zester.id)
DrinkTool.create('drink_id': milk_punch.id, 'tool_id': saucepan.id)
DrinkTool.create('drink_id': milk_punch.id, 'tool_id': large_bowl.id)
DrinkTool.create('drink_id': milk_punch.id, 'tool_id': jelly_bag.id)

craftwerk_manhattan_image = File.open('app/assets/images/craftwerkManhattan.jpg')
craftwerk_manhattan = Drink.create('name': 'Cr&ftwerk Manhattan', 'directions': 'Add Ingredients To Mixing Glass. Fill With Ice. Stir and strain into a chilled cocktail glass. Garnish with an orange twist.',
'image': craftwerk_manhattan_image)
DrinkGenre.create('drink_id': craftwerk_manhattan.id, 'genre_id': brostep.id)
DrinkGenre.create('drink_id': craftwerk_manhattan.id, 'genre_id': skate_punk.id)
DrinkGenre.create('drink_id': craftwerk_manhattan.id, 'genre_id': experimental.id)
DrinkGenre.create('drink_id': craftwerk_manhattan.id, 'genre_id': neoclassical.id)
DrinkGenre.create('drink_id': craftwerk_manhattan.id, 'genre_id': post_grunge.id)
DrinkIngredient.create('drink_id': craftwerk_manhattan.id, 'ingredient_id': two_craftwerk.id)
DrinkIngredient.create('drink_id': craftwerk_manhattan.id, 'ingredient_id': dolin_rouge.id)
DrinkIngredient.create('drink_id': craftwerk_manhattan.id, 'ingredient_id': luxardo.id)
DrinkIngredient.create('drink_id': craftwerk_manhattan.id, 'ingredient_id': three_angs.id)
DrinkTool.create('drink_id': craftwerk_manhattan.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': craftwerk_manhattan.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': craftwerk_manhattan.id, 'tool_id': julep_strainer.id)

coffee_cocktail_image = File.open('app/assets/images/coffeeCocktail.jpg')
coffee_cocktail = Drink.create('name': 'Coffee Cocktail', 'directions': 'Break egg into shaker. Add powdered sugar, port wine, brandy and ice. Shake well and strain into a chilled coupe.',
'image': coffee_cocktail_image)
DrinkGenre.create('drink_id': coffee_cocktail.id, 'genre_id': hip_hop.id)
DrinkGenre.create('drink_id': coffee_cocktail.id, 'genre_id': underground_hip_hop.id)
DrinkGenre.create('drink_id': coffee_cocktail.id, 'genre_id': dirty_south_rap.id)
DrinkGenre.create('drink_id': coffee_cocktail.id, 'genre_id': funk.id)
DrinkGenre.create('drink_id': coffee_cocktail.id, 'genre_id': blues.id)
DrinkGenre.create('drink_id': coffee_cocktail.id, 'genre_id': motown.id)
DrinkGenre.create('drink_id': coffee_cocktail.id, 'genre_id': r_b.id)
DrinkIngredient.create('drink_id': coffee_cocktail.id, 'ingredient_id': half_brandy.id)
DrinkIngredient.create('drink_id': coffee_cocktail.id, 'ingredient_id': egg.id)
DrinkIngredient.create('drink_id': coffee_cocktail.id, 'ingredient_id': powdered_sugar.id)
DrinkIngredient.create('drink_id': coffee_cocktail.id, 'ingredient_id': one_port_wine.id)
DrinkTool.create('drink_id': coffee_cocktail.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': coffee_cocktail.id, 'tool_id': strainer.id)

suffering_bastard_image = File.open('app/assets/images/sufferingBastard.jpg')
suffering_bastard = Drink.create('name': 'Suffering Bastard', 'directions': 'Combine ingredients in shaker. Add ice and shake. Strain into a glass with ice. Top with ginger beer. Garnish with lime.',
'image': suffering_bastard_image)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': tropical.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': reggae_fusion.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': reggae.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': reggaeton.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': caribbean.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': tropical_house.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': rap.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': trap_music.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': beach_music.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': dirty_south_rap.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': gangster_rap.id)
DrinkIngredient.create('drink_id': suffering_bastard.id, 'ingredient_id': one_american_brandy.id)
DrinkIngredient.create('drink_id': suffering_bastard.id, 'ingredient_id': one_gin.id)
DrinkIngredient.create('drink_id': suffering_bastard.id, 'ingredient_id': lg_lime.id)
DrinkIngredient.create('drink_id': suffering_bastard.id, 'ingredient_id': half_simple_syrup.id)
DrinkIngredient.create('drink_id': suffering_bastard.id, 'ingredient_id': one_ang.id)
DrinkIngredient.create('drink_id': suffering_bastard.id, 'ingredient_id': ginger_beer.id)
DrinkIngredient.create('drink_id': suffering_bastard.id, 'ingredient_id': half_orgeat.id)
DrinkTool.create('drink_id': suffering_bastard.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': suffering_bastard.id, 'tool_id': hawthorne_strainer.id)

scorpion_image = File.open('app/assets/images/scorpion.jpg')
scorpion = Drink.create('name': 'Scorpion', 'directions': 'Combine ingredients in shaker. Add ice and shake. Strain into a glass with ice. Garnish with citrus and mint.',
'image': scorpion_image)
DrinkGenre.create('drink_id': scorpion.id, 'genre_id': reggaeton.id)
DrinkGenre.create('drink_id': suffering_bastard.id, 'genre_id': reggae.id)
DrinkGenre.create('drink_id': scorpion.id, 'genre_id': latin_alternative.id)
DrinkGenre.create('drink_id': scorpion.id, 'genre_id': new_rave.id)
DrinkGenre.create('drink_id': scorpion.id, 'genre_id': tropical.id)
DrinkGenre.create('drink_id': scorpion.id, 'genre_id': beach_music.id)
DrinkGenre.create('drink_id': scorpion.id, 'genre_id': swedish_pop.id)
DrinkGenre.create('drink_id': scorpion.id, 'genre_id': pop.id)
DrinkGenre.create('drink_id': scorpion.id, 'genre_id': tropical_house.id)
DrinkGenre.create('drink_id': scorpion.id, 'genre_id': house.id)
DrinkIngredient.create('drink_id': scorpion.id, 'ingredient_id': one_american_brandy.id)
DrinkIngredient.create('drink_id': scorpion.id, 'ingredient_id': half_gin.id)
DrinkIngredient.create('drink_id': scorpion.id, 'ingredient_id': half_aged_rum.id)
DrinkIngredient.create('drink_id': scorpion.id, 'ingredient_id': one_orange_juice.id)
DrinkIngredient.create('drink_id': scorpion.id, 'ingredient_id': lg_lime.id)
DrinkIngredient.create('drink_id': scorpion.id, 'ingredient_id': simple_syrup75.id)
DrinkIngredient.create('drink_id': scorpion.id, 'ingredient_id': half_orgeat.id)
DrinkTool.create('drink_id': scorpion.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': scorpion.id, 'tool_id': hawthorne_strainer.id)

saturn_image = File.open('app/assets/images/saturn.jpg')
saturn = Drink.create('name': 'Saturn', 'directions': 'Add ingredients with ice to shaker, shake and pour in a tiki glass with crushed ice. Garnish with a orchid and lemon wheel',
'image': saturn_image)
DrinkGenre.create('drink_id': saturn.id, 'genre_id': alt_90s.id)
DrinkGenre.create('drink_id': saturn.id, 'genre_id': tropical.id)
DrinkGenre.create('drink_id': saturn.id, 'genre_id': beach_music.id)
DrinkGenre.create('drink_id': saturn.id, 'genre_id': ukulele.id)
DrinkGenre.create('drink_id': saturn.id, 'genre_id': new_wave.id)
DrinkGenre.create('drink_id': saturn.id, 'genre_id': new_wave_pop.id)
DrinkGenre.create('drink_id': saturn.id, 'genre_id': alternative_dance.id)
DrinkGenre.create('drink_id': saturn.id, 'genre_id': filter_house.id)
DrinkIngredient.create('drink_id': saturn.id, 'ingredient_id': onefive_american_gin.id)
DrinkIngredient.create('drink_id': saturn.id, 'ingredient_id': lemon_juice75.id)
DrinkIngredient.create('drink_id': saturn.id, 'ingredient_id': falernum25.id)
DrinkIngredient.create('drink_id': saturn.id, 'ingredient_id': half_orgeat.id)
DrinkIngredient.create('drink_id': saturn.id, 'ingredient_id': half_passionfruit.id)
DrinkTool.create('drink_id': saturn.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': saturn.id, 'tool_id': hawthorne_strainer.id)

southside_image = File.open('app/assets/images/southside.jpg')
southside = Drink.create('name': 'Southside', 'directions': 'Combine ingredients in shaker. Add ice and shake. Strain into a chilled coupe. Garnish with one mint leaf, smacked to release the oils, floating on top of the cocktail.',
'image': southside_image)
DrinkGenre.create('drink_id': southside.id, 'genre_id': rap.id)
DrinkGenre.create('drink_id': southside.id, 'genre_id': underground_hip_hop.id)
DrinkGenre.create('drink_id': southside.id, 'genre_id': chicago_soul.id)
DrinkGenre.create('drink_id': southside.id, 'genre_id': chicago_hip_hop.id)
DrinkGenre.create('drink_id': southside.id, 'genre_id': pop.id)
DrinkGenre.create('drink_id': southside.id, 'genre_id': dance_pop.id)
DrinkGenre.create('drink_id': southside.id, 'genre_id': chicago_soul.id)
DrinkIngredient.create('drink_id': southside.id, 'ingredient_id': american_gin.id)
DrinkIngredient.create('drink_id': southside.id, 'ingredient_id': one_lime.id)
DrinkIngredient.create('drink_id': southside.id, 'ingredient_id': simple_syrup75.id)
DrinkIngredient.create('drink_id': southside.id, 'ingredient_id': sprig_mint.id)
DrinkTool.create('drink_id': southside.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': southside.id, 'tool_id': hawthorne_strainer.id)

gimlet_image = File.open('app/assets/images/gimlet.jpg')
gimlet = Drink.create('name': 'Gimlet', 'directions': 'Combine the gin and lime juice with ice in a shaker and shake until chilled. Strain into a chilled glass and garnish.',
'image': gimlet_image)
DrinkGenre.create('drink_id': gimlet.id, 'genre_id': british_pop.id)
DrinkGenre.create('drink_id': gimlet.id, 'genre_id': deep_chiptune.id)
DrinkGenre.create('drink_id': gimlet.id, 'genre_id': show_tunes.id)
DrinkGenre.create('drink_id': gimlet.id, 'genre_id': broadway.id)
DrinkGenre.create('drink_id': gimlet.id, 'genre_id': filter_house.id)
DrinkIngredient.create('drink_id': gimlet.id, 'ingredient_id': american_gin.id)
DrinkIngredient.create('drink_id': gimlet.id, 'ingredient_id': roses_lime75.id)
DrinkTool.create('drink_id': gimlet.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': gimlet.id, 'tool_id': hawthorne_strainer.id)

aviation_image = File.open('app/assets/images/aviation.jpg')
aviation = Drink.create('name': 'Aviation', 'directions': 'Shake ingredients with ice, then strain into a chilled glass. Garnish with a brandied cocktail cherry.',
'image': aviation_image)
DrinkGenre.create('drink_id': aviation.id, 'genre_id': chillwave.id)
DrinkGenre.create('drink_id': aviation.id, 'genre_id': compositional_ambient.id)
DrinkGenre.create('drink_id': aviation.id, 'genre_id': synth.id)
DrinkGenre.create('drink_id': aviation.id, 'genre_id': art_pop.id)
DrinkGenre.create('drink_id': aviation.id, 'genre_id': shoegaze.id)
DrinkGenre.create('drink_id': aviation.id, 'genre_id': metropopolis.id)
DrinkGenre.create('drink_id': aviation.id, 'genre_id': new_rave.id)
DrinkGenre.create('drink_id': aviation.id, 'genre_id': permanent_wave.id)
DrinkIngredient.create('drink_id': aviation.id, 'ingredient_id': onefive_american_gin.id)
DrinkIngredient.create('drink_id': aviation.id, 'ingredient_id': lemon_juice75.id)
DrinkIngredient.create('drink_id': aviation.id, 'ingredient_id': maraschino_liqueur75.id)
DrinkIngredient.create('drink_id': aviation.id, 'ingredient_id': creme_violette.id)
DrinkTool.create('drink_id': aviation.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': aviation.id, 'tool_id': hawthorne_strainer.id)

french75_image = File.open('app/assets/images/french75.jpg')
french75 = Drink.create('name': 'French 75', 'directions': 'Add ingredients to shaker filled with ice. Shake and pour into highball glass filled with ice. Top with Champagne.',
'image': french75_image)
DrinkGenre.create('drink_id': french75.id, 'genre_id': indie_rb.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': francais.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': hollywood.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': pop_rap.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': catstep.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': tracestep.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': trap_francais.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': europop.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': filter_house.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': pop.id)
DrinkGenre.create('drink_id': french75.id, 'genre_id': chanson.id)
DrinkIngredient.create('drink_id': french75.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': french75.id, 'ingredient_id': one_lemon_juice.id)
DrinkIngredient.create('drink_id': french75.id, 'ingredient_id': champagne.id)
DrinkTool.create('drink_id': french75.id, 'tool_id': boston_shaker.id)

sidecar_image = File.open('app/assets/images/sidecar.jpg')
sidecar = Drink.create('name': 'Sidecar', 'directions': 'Fill a shaker half full of ice, add ingredients. Shake well and strain into a coupe.',
'image': sidecar_image)
DrinkGenre.create('drink_id': sidecar.id, 'genre_id': neo_psychadelic.id)
DrinkGenre.create('drink_id': sidecar.id, 'genre_id': modern_rock.id)
DrinkGenre.create('drink_id': sidecar.id, 'genre_id': southern_rock.id)
DrinkGenre.create('drink_id': sidecar.id, 'genre_id': pop_rock.id)
DrinkGenre.create('drink_id': sidecar.id, 'genre_id': canadian.id)
DrinkGenre.create('drink_id': sidecar.id, 'genre_id': stomp_whittle.id)
DrinkIngredient.create('drink_id': sidecar.id, 'ingredient_id': one_american_brandy.id)
DrinkIngredient.create('drink_id': sidecar.id, 'ingredient_id': one_lemon_juice.id)
DrinkIngredient.create('drink_id': sidecar.id, 'ingredient_id': one_destillare.id)
DrinkTool.create('drink_id': sidecar.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': sidecar.id, 'tool_id': strainer.id)

montana_image = File.open('app/assets/images/montana.jpg')
montana = Drink.create('name': 'Montana', 'directions': 'Fill mixing glass halfway with ice. Add ingredients, stir and strain into coupe.  Garnish with olives and serve.',
'image': montana_image)
DrinkGenre.create('drink_id': montana.id, 'genre_id': album_rock.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': country.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': modern_country_rock.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': bluegrass.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': stomp_whittle.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': stomp_holler.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': alternative_country.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': classic_rock.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': traditional_country.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': redneck.id)
DrinkGenre.create('drink_id': montana.id, 'genre_id': outlaw_country.id)
DrinkIngredient.create('drink_id': montana.id, 'ingredient_id': onefive_american_brandy.id)
DrinkIngredient.create('drink_id': montana.id, 'ingredient_id': two_angs.id)
DrinkIngredient.create('drink_id': montana.id, 'ingredient_id': onefive_vermouth.id)
DrinkIngredient.create('drink_id': montana.id, 'ingredient_id': two_anisette.id)
DrinkTool.create('drink_id': montana.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': montana.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': montana.id, 'tool_id': strainer.id)

east_india_image = File.open('app/assets/images/eastIndia.jpg')
east_india = Drink.create('name': 'East India', 'directions': 'Fill mixing glass with shaved ice. Add ingredients, stir with a spoon and strain into a chilled coupe. Garnish with a cherry, twist a piece of lemon peel on top, and serve.',
'image': east_india_image)
DrinkGenre.create('drink_id': east_india.id, 'genre_id': indian_classical.id)
DrinkGenre.create('drink_id': east_india.id, 'genre_id': freak_folk.id)
DrinkGenre.create('drink_id': east_india.id, 'genre_id': sitar.id)
DrinkGenre.create('drink_id': east_india.id, 'genre_id': exotica.id)
DrinkGenre.create('drink_id': east_india.id, 'genre_id': show_tunes.id)
DrinkGenre.create('drink_id': east_india.id, 'genre_id': swedish.id)
DrinkGenre.create('drink_id': east_india.id, 'genre_id': bollywood.id)
DrinkIngredient.create('drink_id': east_india.id, 'ingredient_id': twofive_american_brandy.id)
DrinkIngredient.create('drink_id': east_india.id, 'ingredient_id': one_curacao.id)
DrinkIngredient.create('drink_id': east_india.id, 'ingredient_id': one_pineapple.id)
DrinkIngredient.create('drink_id': east_india.id, 'ingredient_id': two_bokers.id)
DrinkIngredient.create('drink_id': east_india.id, 'ingredient_id': two_maraschino.id)
DrinkTool.create('drink_id': east_india.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': east_india.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': east_india.id, 'tool_id': strainer.id)
DrinkTool.create('drink_id': east_india.id, 'tool_id': knife.id)

singapore_sling_image = File.open('app/assets/images/singaporeSling.jpg')
singapore_sling = Drink.create('name': 'Singapore Sling', 'directions': 'Combine ingredients in shaker. Add ice and shake. Strain into A highball glass with ice. Add splash of soda water and drizzle cherry brandy on top. Garnish with citrus and a brandied cocktail cherry.',
'image': singapore_sling_image)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': synth_pop.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': new_jack_swing.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': malaysian.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': oriental_groove.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': malaysian_hip_hop.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': thai_hip_hop.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': tropical.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': disco.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': nineteen_eighties.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': mandopop.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': retro_electro.id)
DrinkGenre.create('drink_id': singapore_sling.id, 'genre_id': disco.id)
DrinkIngredient.create('drink_id': singapore_sling.id, 'ingredient_id': onefive_american_gin.id)
DrinkIngredient.create('drink_id': singapore_sling.id, 'ingredient_id': one_orange_juice.id)
DrinkIngredient.create('drink_id': singapore_sling.id, 'ingredient_id': quarter_benedictine.id)
DrinkIngredient.create('drink_id': singapore_sling.id, 'ingredient_id': drizzle_cherry.id)
DrinkIngredient.create('drink_id': singapore_sling.id, 'ingredient_id': soda_water.id)
DrinkTool.create('drink_id': singapore_sling.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': singapore_sling.id, 'tool_id': hawthorne_strainer.id)


japanese_image = File.open('app/assets/images/japanese.jpg')
japanese = Drink.create('name': 'Japanese Cocktail', 'directions': 'Fill the mixing glass ⅓ full of ice, add ingredients and stir with spoon. Strain into chilled coupe. Garnish with a lemon peel.',
'image': japanese_image)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': deep_house.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': tropical.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': japanese_city_pop.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': k_hop.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': j_poprock.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': edm.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': electronic.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': complextro.id)
DrinkGenre.create('drink_id': japanese.id, 'genre_id': retro_electro.id)
DrinkIngredient.create('drink_id': japanese.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': japanese.id, 'ingredient_id': one_orgeat.id)
DrinkIngredient.create('drink_id': japanese.id, 'ingredient_id': four_angs.id)
DrinkTool.create('drink_id': japanese.id, 'tool_id': strainer.id)
DrinkTool.create('drink_id': japanese.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': japanese.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': japanese.id, 'tool_id': knife.id)

marconi_wireless_image = File.open('app/assets/images/marconiWireless.jpg')
marconi_wireless = Drink.create('name': 'The Marconi Wireless', 'directions': 'Stir, strain into a chilled cocktail glass.  Garnish with either a cherry or a lemon peel.',
'image': marconi_wireless_image)
DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': modern_rock.id)
DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': garage_rock.id)
DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': freak_folk.id)
DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': lofi.id)
DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': compositional_ambient.id)
DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': focus.id)
DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': comic.id)
DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': experimental.id)
DrinkGenre.create('drink_id': marconi_wireless.id, 'genre_id': electronic.id)
DrinkIngredient.create('drink_id': marconi_wireless.id, 'ingredient_id': two_apple_brandy.id)
DrinkIngredient.create('drink_id': marconi_wireless.id, 'ingredient_id': one_vermouth.id)
DrinkIngredient.create('drink_id': marconi_wireless.id, 'ingredient_id': two_orange_bitters.id)
DrinkTool.create('drink_id': marconi_wireless.id, 'tool_id': jigger.id)
DrinkTool.create('drink_id': marconi_wireless.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': marconi_wireless.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': marconi_wireless.id, 'tool_id': hawthorne_strainer.id)

vieux_carre_image = File.open('app/assets/images/vieuxCarre.jpg')
vieux_carre = Drink.create('name': 'Vieux Carré', 'directions': 'Combine ingredients in mixing glass and fill with ice. Stir well, strain into an ice-filled cocktail glass and garnish with a brandied cherry, lemon twist or both.',
'image': vieux_carre_image)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': jazz_blues.id)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': underground_hip_hop.id)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': dirty_south_hip_hop.id)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': french_hip_hop.id)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': southern_hip_hop.id)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': trap_music.id)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': free_jazz.id)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': free_improvisation.id)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': blues.id)
DrinkGenre.create('drink_id': vieux_carre.id, 'genre_id': soul.id)
DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': one_american_brandy.id)
DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': one_high_west.id)
DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': one_vermouth.id)
DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': half_benedictine.id)
DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': two_angs.id)
DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': pehchauds_bitters.id)
DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': twist_orange.id)
DrinkIngredient.create('drink_id': vieux_carre.id, 'ingredient_id': brandied_cherry.id)
DrinkTool.create('drink_id': vieux_carre.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': vieux_carre.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': vieux_carre.id, 'tool_id': julep_strainer.id)

the_ritual_image = File.open('app/assets/images/theRitual.jpg')
the_ritual = Drink.create('name': 'The Ritual', 'directions': 'Add Absinthe to glass. Slowly drizzle a trickle of ice cold water to the spirit watching closely as it mixes with the Absinthe. When the water to absinthe ratio reaches somewhere between 1:3 & 1:5 (depending on your taste), the essential oils which are dissolved in the absinthe during distillation will emulsify with the water and create the translucent cloudy effect known as the "louche."',
'image': the_ritual_image, 'tips': 'Due to the exquisite nature of our craft absinthe we do not ascribe to the traditional use of sugar. As with everything, we’ll leave it to your personal taste.')
DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': death_metal.id)
DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': psychadelic_rock.id)
DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': chillwave.id)
DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': christian_music.id)
DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': neoclassical_metal.id)
DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': gospel.id)
DrinkGenre.create('drink_id': the_ritual.id, 'genre_id': post_grunge.id)
DrinkIngredient.create('drink_id': the_ritual.id, 'ingredient_id': absinthe_blanche_onefive.id)
DrinkIngredient.create('drink_id': the_ritual.id, 'ingredient_id': ice_water.id)
DrinkTool.create('drink_id': the_ritual.id, 'tool_id': glass.id)
DrinkTool.create('drink_id': the_ritual.id, 'tool_id': pitcher.id)

standard_collins_image = File.open('app/assets/images/standardCollins.jpg')
standard_collins = Drink.create('name': 'Standard (Tom) Collins', 'directions': 'Combine brandy, lemon juice, and syrup in shaker tin, shake with ice. Strain into collins glass, add fresh ice, top with soda. Garnish with lemon wheel.',
'image': standard_collins_image, 'tips': 'Fresh lemon juice (less than 8 hours old) works best in this recipe.')
DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': motown.id)
DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': synth_pop.id)
DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': art_pop.id)
DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': comic.id)
DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': comedy_rock.id)
DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': pop_rock.id)
DrinkGenre.create('drink_id': standard_collins.id, 'genre_id': filter_house.id)
DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': two_immature.id)
DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': one_lemon_juice.id)
DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': one_simple_syrup.id)
DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': lemon_wheel.id)
DrinkIngredient.create('drink_id': standard_collins.id, 'ingredient_id': two_club_soda.id)
DrinkTool.create('drink_id': standard_collins.id, 'tool_id': shaker_tins.id)
DrinkTool.create('drink_id': standard_collins.id, 'tool_id': hawthorne_strainer.id)
DrinkTool.create('drink_id': standard_collins.id, 'tool_id': jigger.id)
DrinkTool.create('drink_id': standard_collins.id, 'tool_id': collins_glass.id)

brandy_sour_image = File.open('app/assets/images/brandySour.jpg')
brandy_sour = Drink.create('name': 'Brandy Sour', 'directions': 'Add all the ingredients to a Boston shaker and fill with ice. Shake vigorously and strain into a rocks glass. Garnish with a lime wheel and 3 gentle drops of angostura bitters, which will settle in the foam of the cocktail. Using a straw, swirl the bitters into a simple design.',
'image': brandy_sour_image, 'tips': 'Remove the whisk from the hawthorn strainer and place it into the mixing glass prior to shaking for added aeration.')
DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': acoustic_pop.id)
DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': indie_rb.id)
DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': gypsy_folk.id)
DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': greek.id)
DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': rebetika.id)
DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': bay_hip_hop.id)
DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': easy_listening.id)
DrinkGenre.create('drink_id': brandy_sour.id, 'genre_id': europop.id)
DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': two_immature.id)
DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': one_lime.id)
DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': one_simple_syrup.id)
DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': lime_wheel.id)
DrinkIngredient.create('drink_id': brandy_sour.id, 'ingredient_id': half_egg.id)
DrinkTool.create('drink_id': brandy_sour.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': brandy_sour.id, 'tool_id': hawthorne_strainer.id)
DrinkTool.create('drink_id': brandy_sour.id, 'tool_id': straw.id)

sazerac_image = File.open('app/assets/images/sazerac.jpg')
sazerac = Drink.create('name': 'Sazerac', 'directions': 'Muddle the sugar and bitters, then add the Brandy and ice. Stir and strain into a chilled, Absinthe rinsed rocks glass. Twist a Lemon Peel over the surface and discard.',
'image': sazerac_image)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': southern.id)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': hip_hop.id)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': ragtime.id)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': jazz.id)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': vintage_jazz.id)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': new_orleans_jazz.id)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': southern_soul.id)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': french.id)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': free_improvisation.id)
DrinkGenre.create('drink_id': sazerac.id, 'genre_id': roots_rock.id)
DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': three_peychauds_bitters.id)
DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': demerara_cube.id)
DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': absinthe_rinse.id)
DrinkIngredient.create('drink_id': sazerac.id, 'ingredient_id': lemon_twist.id)
DrinkTool.create('drink_id': sazerac.id, 'tool_id': muddler.id)
DrinkTool.create('drink_id': sazerac.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': sazerac.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': sazerac.id, 'tool_id': strainer.id)


mule_image = File.open('app/assets/images/mule.jpg')
mule = Drink.create('name': 'Mule', 'directions': 'Combine all ingredients in highball glass, add ice. Garnish with lime wedge.',
'image': mule_image)
DrinkGenre.create('drink_id': mule.id, 'genre_id': new_wave.id)
DrinkGenre.create('drink_id': mule.id, 'genre_id': alternative_rock.id)
DrinkGenre.create('drink_id': mule.id, 'genre_id': remix.id)
DrinkGenre.create('drink_id': mule.id, 'genre_id': british.id)
DrinkGenre.create('drink_id': mule.id, 'genre_id': punk.id)
DrinkGenre.create('drink_id': mule.id, 'genre_id': garage_rock.id)
DrinkGenre.create('drink_id': mule.id, 'genre_id': album_rock.id)
DrinkGenre.create('drink_id': mule.id, 'genre_id': skate_punk.id)
DrinkGenre.create('drink_id': mule.id, 'genre_id': dark_wave.id)
DrinkGenre.create('drink_id': mule.id, 'genre_id': hollywood.id)
DrinkIngredient.create('drink_id': mule.id, 'ingredient_id': two_immature.id)
DrinkIngredient.create('drink_id': mule.id, 'ingredient_id': med_lime.id)
DrinkIngredient.create('drink_id': mule.id, 'ingredient_id': four_ginger_beer.id)
DrinkIngredient.create('drink_id': mule.id, 'ingredient_id': lime_wedge.id)
DrinkTool.create('drink_id': mule.id, 'tool_id': jigger.id)
DrinkTool.create('drink_id': mule.id, 'tool_id': highball_glass.id)

metropolitan_image = File.open('app/assets/images/metropolitan.jpg')
metropolitan = Drink.create('name': 'Metropolitan', 'directions': 'Combine ingredients in mixing glass. Add ice. Stir until well chilled. Strain into cocktail glass. garnish with a lemon twist.',
'image': metropolitan_image)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': classical.id)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': ballads.id)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': compositional_ambient.id)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': lounge.id)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': neoclassical.id)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': soundtrack.id)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': cabaret.id)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': classify.id)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': free_jazz.id)
DrinkGenre.create('drink_id': metropolitan.id, 'genre_id': free_improvisation.id)
DrinkIngredient.create('drink_id': metropolitan.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': metropolitan.id, 'ingredient_id': one_vermouth.id)
DrinkIngredient.create('drink_id': metropolitan.id, 'ingredient_id': two_angs.id)
DrinkIngredient.create('drink_id': metropolitan.id, 'ingredient_id': demerara_syrup.id)
DrinkTool.create('drink_id': metropolitan.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': metropolitan.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': metropolitan.id, 'tool_id': julep_strainer.id)

margarita_image = File.open('app/assets/images/margarita.jpg')
margarita = Drink.create('name': 'Margarita', 'directions': 'Combine ingredients in shaker. Add ice & shake. Strain into a salt rimmed rocks glass. Garnish with a lime wheel.',
'image': margarita_image)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': mexican_pop.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': spanish.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': mellow_gold.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': easy_listening.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': neo_mellow.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': mexican.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': hollywood.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': texas_country.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': outlaw_country.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': filter_house.id)
DrinkGenre.create('drink_id': margarita.id, 'genre_id': rock_espanol.id)
DrinkIngredient.create('drink_id': margarita.id, 'ingredient_id': casa_noble.id)
DrinkIngredient.create('drink_id': margarita.id, 'ingredient_id': ofive_destillare.id)
DrinkIngredient.create('drink_id': margarita.id, 'ingredient_id': lg_lime.id)
DrinkIngredient.create('drink_id': margarita.id, 'ingredient_id': quarter_simple_syrup.id)
DrinkTool.create('drink_id': margarita.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': margarita.id, 'tool_id': hawthorne_strainer.id)

julep_image = File.open('app/assets/images/julep.jpg')
julep = Drink.create('name': 'Julep', 'directions': 'Combine all ingredients in mixing glass. Muddle mint leaves. Strain liquid into glass, fill with crushed ice to heaping. Garnish with mint leaves.',
'image': julep_image)
DrinkGenre.create('drink_id': julep.id, 'genre_id': americana.id)
DrinkGenre.create('drink_id': julep.id, 'genre_id': folk.id)
DrinkGenre.create('drink_id': julep.id, 'genre_id': country_road.id)
DrinkGenre.create('drink_id': julep.id, 'genre_id': stomp_holler.id)
DrinkGenre.create('drink_id': julep.id, 'genre_id': mellow_gold.id)
DrinkGenre.create('drink_id': julep.id, 'genre_id': new_americana.id)
DrinkGenre.create('drink_id': julep.id, 'genre_id': traditional_country.id)
DrinkIngredient.create('drink_id': julep.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': julep.id, 'ingredient_id': half_simple_syrup.id)
DrinkIngredient.create('drink_id': julep.id, 'ingredient_id': mint_leaves.id)
DrinkTool.create('drink_id': julep.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': julep.id, 'tool_id': muddler.id)
DrinkTool.create('drink_id': julep.id, 'tool_id': julep_strainer.id)
DrinkTool.create('drink_id': julep.id, 'tool_id': lewis_bag.id)
DrinkTool.create('drink_id': julep.id, 'tool_id': mallet.id)


jack_rose_image = File.open('app/assets/images/jackRose.jpg')
jack_rose = Drink.create('name': 'Jack Rose', 'directions': 'Pour ingredients into a mixing glass and fill with ice. Shake well with a Boston shaker. Strain into a chilled coupe, garnish with a twist of lemon.',
'image': jack_rose_image, 'tips': 'Heat 2 cups each fresh pomegranate juice and unbleached sugar with 2 oz. pomegranate molasses and 1 tsp. orange blossom water for simple, perfect homemade grenadine.')
DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': rock_roll.id)
DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': singer_songwriter.id)
DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': classic_rock.id)
DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': hard_rock.id)
DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': drumline.id)
DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': rock.id)
DrinkGenre.create('drink_id': jack_rose.id, 'genre_id': roots_rock.id)
DrinkIngredient.create('drink_id': jack_rose.id, 'ingredient_id': two_apple_brandy.id)
DrinkIngredient.create('drink_id': jack_rose.id, 'ingredient_id': grenadine.id)
DrinkIngredient.create('drink_id': jack_rose.id, 'ingredient_id': lg_lime.id)
DrinkTool.create('drink_id': jack_rose.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': jack_rose.id, 'tool_id': hawthorne_strainer.id)

horses_neck_image = File.open('app/assets/images/horsesNeck.jpg')
horses_neck = Drink.create('name': 'Horses Neck', 'directions': 'Combine brandy and ginger beer in highball glass. Add ice. Garnish with generously long lemon peel. Add dash of bitters on top.',
'image': horses_neck_image, 'tips': 'A potato peeler or “y” peeler will work best to achieve the long lemon peel garnish.')
DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': classical.id)
DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': disco.id)
DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': funk.id)
DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': ska.id)
DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': modern_rock.id)
DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': garage_rock.id)
DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': glam_metal.id)
DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': pop_emo.id)
DrinkGenre.create('drink_id': horses_neck.id, 'genre_id': new_wave.id)
DrinkIngredient.create('drink_id': horses_neck.id, 'ingredient_id': onefive_american_brandy.id)
DrinkIngredient.create('drink_id': horses_neck.id, 'ingredient_id': four_ginger_beer.id)
DrinkIngredient.create('drink_id': horses_neck.id, 'ingredient_id': one_ang.id)
DrinkIngredient.create('drink_id': horses_neck.id, 'ingredient_id': lemon.id)
DrinkTool.create('drink_id': horses_neck.id, 'tool_id': peeler.id)
DrinkTool.create('drink_id': horses_neck.id, 'tool_id': jigger.id)
DrinkTool.create('drink_id': horses_neck.id, 'tool_id': highball_glass.id)

harvard_image = File.open('app/assets/images/harvard.jpg')
harvard = Drink.create('name': 'Harvard', 'directions': 'Combine brandy, vermouth and bitters in mixing glass. Fill with ice. Stir until well chilled. Strain into cocktail glass and top with cold club soda.',
'image': harvard_image)
DrinkGenre.create('drink_id': harvard.id, 'genre_id': classic_rock.id)
DrinkGenre.create('drink_id': harvard.id, 'genre_id': rock_roll.id)
DrinkGenre.create('drink_id': harvard.id, 'genre_id': indie_rock.id)
DrinkGenre.create('drink_id': harvard.id, 'genre_id': britpop.id)
DrinkGenre.create('drink_id': harvard.id, 'genre_id': singer_songwriter.id)
DrinkGenre.create('drink_id': harvard.id, 'genre_id': modern_rock.id)
DrinkGenre.create('drink_id': harvard.id, 'genre_id': album_rock.id)
DrinkGenre.create('drink_id': harvard.id, 'genre_id': new_wave_pop.id)
DrinkGenre.create('drink_id': harvard.id, 'genre_id': new_rave.id)
DrinkIngredient.create('drink_id': harvard.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': harvard.id, 'ingredient_id': one_vermouth.id)
DrinkIngredient.create('drink_id': harvard.id, 'ingredient_id': club_soda.id)
DrinkIngredient.create('drink_id': harvard.id, 'ingredient_id': two_angs.id)
DrinkTool.create('drink_id': harvard.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': harvard.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': harvard.id, 'tool_id': julep_strainer.id)

fish_house_punch_image = File.open('app/assets/images/fishHousePunch.jpg')
fish_house_punch = Drink.create('name': 'Fish House Punch', 'directions': 'In a large bowl, add simple syrup and lemon peels, rub together to release the citrus oils into the sugar. Allow infusing for at least 30 minutes. Strain off the peels. Add brandy, rum, lemon juice and peach liqueur. Stir to mix. Add block of ice to chill. Allow thirty minutes for dilution. Garnish with lemon wheels and ladle into individual glasses. (serves 2-4)',
'image': fish_house_punch_image, 'tips': 'For easy frozen ice blocks at home, fill a 16 oz. plastic storage container with water and freeze overnight. Just before serving, remove the container from the freezer and leave upside-down for a couple minutes. The ice cube will slide right out.')
DrinkGenre.create('drink_id': fish_house_punch.id, 'genre_id': house.id)
DrinkGenre.create('drink_id': fish_house_punch.id, 'genre_id': progressive.id)
DrinkGenre.create('drink_id': fish_house_punch.id, 'genre_id': british_blues.id)
DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lg_american_brandy.id)
DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lg_peach_liqueur.id)
DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lg_jamaican_rum.id)
DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': simple_syrup.id)
DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lg_filtered_water.id)
DrinkIngredient.create('drink_id': fish_house_punch.id, 'ingredient_id': lemon_peels.id)
DrinkTool.create('drink_id': fish_house_punch.id, 'tool_id': punch_bowl.id)
DrinkTool.create('drink_id': fish_house_punch.id, 'tool_id': ladle.id)

daisy_image = File.open('app/assets/images/daisy.jpg')
daisy = Drink.create('name': 'Daisy', 'directions': 'Pour brandy, orange liqueur and lemon into a mixing glass and fill with ice. Shake well with a Boston shaker. Strain into chilled cocktail glass and top with two dashes of club soda.',
'image': daisy_image)
DrinkGenre.create('drink_id': daisy.id, 'genre_id': country.id)
DrinkGenre.create('drink_id': daisy.id, 'genre_id': folk.id)
DrinkGenre.create('drink_id': daisy.id, 'genre_id': indie_folk.id)
DrinkGenre.create('drink_id': daisy.id, 'genre_id': new_wave.id)
DrinkGenre.create('drink_id': daisy.id, 'genre_id': neo_psychadelic.id)
DrinkGenre.create('drink_id': daisy.id, 'genre_id': freak_folk.id)
DrinkGenre.create('drink_id': daisy.id, 'genre_id': neo_mellow.id)
DrinkGenre.create('drink_id': daisy.id, 'genre_id': stomp_whittle.id)
DrinkGenre.create('drink_id': daisy.id, 'genre_id': new_americana.id)
DrinkIngredient.create('drink_id': daisy.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': daisy.id, 'ingredient_id': orange_liqueur75.id)
DrinkIngredient.create('drink_id': daisy.id, 'ingredient_id': lg_lime.id)
DrinkIngredient.create('drink_id': daisy.id, 'ingredient_id': club_soda.id)
DrinkTool.create('drink_id': daisy.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': daisy.id, 'tool_id': hawthorne_strainer.id)

chrysanthemum_image = File.open('app/assets/images/chrysanthemum.jpg')
chrysanthemum = Drink.create('name': 'Chrysanthemum', 'directions': 'Shake with ice. Strain into cocktail glass. Squeeze orange peel on top.',
'image': chrysanthemum_image)
DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': psychadelic_rock.id)
DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': garage_rock.id)
DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': chillwave.id)
DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': freak_folk.id)
DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': experimental.id)
DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': pixie.id)
DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': laboratorio.id)
DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': permanent_wave.id)
DrinkGenre.create('drink_id': chrysanthemum.id, 'genre_id': neo_psychadelic.id)
DrinkIngredient.create('drink_id': chrysanthemum.id, 'ingredient_id': three_absinthe_blanche.id)
DrinkIngredient.create('drink_id': chrysanthemum.id, 'ingredient_id': one_benedictine.id)
DrinkIngredient.create('drink_id': chrysanthemum.id, 'ingredient_id': two_french_vermouth.id)
DrinkIngredient.create('drink_id': chrysanthemum.id, 'ingredient_id': orange_peel.id)
DrinkTool.create('drink_id': chrysanthemum.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': chrysanthemum.id, 'tool_id': hawthorne_strainer.id)

corpse_reviver_image = File.open('app/assets/images/corpseReviver.jpg')
corpse_reviver = Drink.create('name': 'Corpse Reviver', 'directions': 'Combine brandy, Apple brandy & sweet vermouth In Mixing glass. Stir with ice. Strain into a chilled cocktail glass.',
'image': corpse_reviver_image)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': hardcore.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': metalcore.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': emo.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': lofi.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': neo_psychadelic.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': garage_rock.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': hard_rock.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': pop_emo.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': deep_chiptune.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': progressive_metal.id)
DrinkGenre.create('drink_id': corpse_reviver.id, 'genre_id': grime.id)
DrinkIngredient.create('drink_id': corpse_reviver.id, 'ingredient_id': one_american_brandy.id)
DrinkIngredient.create('drink_id': corpse_reviver.id, 'ingredient_id': one_apple_brandy.id)
DrinkIngredient.create('drink_id': corpse_reviver.id, 'ingredient_id': one_vermouth.id)
DrinkTool.create('drink_id': corpse_reviver.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': corpse_reviver.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': corpse_reviver.id, 'tool_id': julep_strainer.id)

old_fash_brandy_image = File.open('app/assets/images/oldFashBrandy.jpg')
old_fash_brandy = Drink.create('name': 'Brandy Old Fashioned', 'directions': 'In a chilled rocks glass, muddle the sugar, bitters, orange wedge and cherry into a thick paste, careful not to work the orange peel. Add brandy, stir, and fill glass with ice and serve.',
'image': old_fash_brandy_image)
DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': adult_standards.id)
DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': crooner_jazz.id)
DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': mellow_gold.id)
DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': singer_songwriter.id)
DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': album_rock.id)
DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': modern_blues.id)
DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': lounge.id)
DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': new_age.id)
DrinkGenre.create('drink_id': old_fash_brandy.id, 'genre_id': funk.id)
DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': sugar_cube.id)
DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': two_angs.id)
DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': thick_orange_wedge.id)
DrinkIngredient.create('drink_id': old_fash_brandy.id, 'ingredient_id': one_amarena.id)
DrinkTool.create('drink_id': old_fash_brandy.id, 'tool_id': muddler.id)
DrinkTool.create('drink_id': old_fash_brandy.id, 'tool_id': bar_spoon.id)

ampersand_image = File.open('app/assets/images/ampersand.jpg')
ampersand = Drink.create('name': 'Ampersand', 'directions': 'Combine ingredients in mixing glass. Add ice and stir. Strain into a cocktail glass. Top with dry curacao. Garnish with an expressed orange peel.',
'image': ampersand_image)
DrinkGenre.create('drink_id': ampersand.id, 'genre_id': piano_rock.id)
DrinkGenre.create('drink_id': ampersand.id, 'genre_id': improvisational_jazz.id)
DrinkGenre.create('drink_id': ampersand.id, 'genre_id': post_bop.id)
DrinkGenre.create('drink_id': ampersand.id, 'genre_id': acoustic_pop.id)
DrinkGenre.create('drink_id': ampersand.id, 'genre_id': modern_rock.id)
DrinkGenre.create('drink_id': ampersand.id, 'genre_id': album_rock.id)
DrinkGenre.create('drink_id': ampersand.id, 'genre_id': canadian_rock.id)
DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': one_american_brandy.id)
DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': one_tom_gin.id)
DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': one_vermouth.id)
DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': bittermens.id)
DrinkIngredient.create('drink_id': ampersand.id, 'ingredient_id': destillare.id)
DrinkTool.create('drink_id': ampersand.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': ampersand.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': ampersand.id, 'tool_id': hawthorne_strainer.id)
DrinkTool.create('drink_id': ampersand.id, 'tool_id': jigger.id)
DrinkTool.create('drink_id': ampersand.id, 'tool_id': citrus_peeler.id)

crusta_image = File.open('app/assets/images/crusta.jpg')
crusta = Drink.create('name': 'Crusta', 'directions': 'Pare the full peel off of the lemon and carefully curl the peel around the inside of the glass. Moisten the rim with cut lemon and dip in superfine sugar, forming a crust on the glass and peel. Combine ingredients in mixing glass. Add ice. Stir and strain into prepared glass.',
'image': crusta_image)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': blues.id)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': southern.id)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': traditional_jazz.id)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': jazz.id)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': classical.id)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': soul_blues.id)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': cajun.id)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': new_orleans_jazz.id)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': dixieland.id)
DrinkGenre.create('drink_id': crusta.id, 'genre_id': ragtime.id)
DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': maraschino_liqueur.id)
DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': lemon_juice.id)
DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': demerara_syrup.id)
DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': pehchauds_bitters.id)
DrinkIngredient.create('drink_id': crusta.id, 'ingredient_id': crushed_ice.id)
DrinkTool.create('drink_id': crusta.id, 'tool_id': mixing_glass.id)
DrinkTool.create('drink_id': crusta.id, 'tool_id': bar_spoon.id)
DrinkTool.create('drink_id': crusta.id, 'tool_id': hawthorne_strainer.id)

almond_crusta_image = File.open('app/assets/images/almondCrusta.jpg')
almond_crusta = Drink.create('name': 'Almond Blossom Crusta', 'directions': 'Prepare the cocktail glass by rubbing the orange wedge around the outside rim and dipping the rim in superfine sugar to form a crust approximately one inch deep. Add all of the ingredients to mixing glass. Fill with ice. Shake vigorously with Boston shaker. Strain into the sugar crusted cocktail glass. Garnish with orange twist.',
'tips': 'To achieve a proper rim on your cocktail, always begin with a non-chilled glass and coordinating citrus.',
'image': almond_crusta_image)
DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': neo_soul.id)
DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': indie_rock.id)
DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': new_americana.id)
DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': indie_anthem_folk.id)
DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': bluegrass.id)
DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': folk_punk.id)
DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': gypsy_punk.id)
DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': neo_psychadelic.id)
DrinkGenre.create('drink_id': almond_crusta.id, 'genre_id': stomp_whittle.id)
DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': onefive_american_brandy.id)
DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': lemon_juice75.id)
DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': orgeat75.id)
DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': superfine_whole.id)
DrinkIngredient.create('drink_id': almond_crusta.id, 'ingredient_id': orange_wedge_twist.id)
DrinkTool.create('drink_id': almond_crusta.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': almond_crusta.id, 'tool_id': hawthorne_strainer.id)

brandy_alexander_image = File.open('app/assets/images/brandyAlexander.jpg')
brandy_alexander = Drink.create('name': 'Brandy Alexander', 'directions': 'Add all the ingredients to a mixing glass and fill with ice. Shake well with a Boston shaker and strain into a chilled coupe. Garnish with freshly grated nutmeg.',
'image': brandy_alexander_image)
DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': r_b.id)
DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': hip_hop.id)
DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': rap.id)
DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': smooth_jazz.id)
DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': quiet_storm.id)
DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': new_jack_swing.id)
DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': focus.id)
DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': cello.id)
DrinkGenre.create('drink_id': brandy_alexander.id, 'genre_id': classify.id)
DrinkIngredient.create('drink_id': brandy_alexander.id, 'ingredient_id': two_american_brandy.id)
DrinkIngredient.create('drink_id': brandy_alexander.id, 'ingredient_id': creme_cacao.id)
DrinkIngredient.create('drink_id': brandy_alexander.id, 'ingredient_id': cream.id)
DrinkIngredient.create('drink_id': brandy_alexander.id, 'ingredient_id': grated_nutmeg.id)
DrinkTool.create('drink_id': brandy_alexander.id, 'tool_id': boston_shaker.id)
DrinkTool.create('drink_id': brandy_alexander.id, 'tool_id': hawthorne_strainer.id)
DrinkTool.create('drink_id': brandy_alexander.id, 'tool_id': zester.id)

death_in_afternoon_image = File.open('app/assets/images/deathInAfternoon.jpg')
death_in_afternoon = Drink.create('name': 'Death In The Afternoon', 'directions': '
  Pour absinthe into a champagne flute and add cold brut champagne until it clouds up. Garnish with a lemon twist.',
'image': death_in_afternoon_image)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': hard_stoner_rock.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': spanish.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': latin_rock.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': cabaret.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': metalcore.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': psychadelic_rock.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': glam_metal.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': pop_emo.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': screamo.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': rock.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': progressive_metal.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': black_metal.id)
DrinkGenre.create('drink_id': death_in_afternoon.id, 'genre_id': death_metal.id)
DrinkIngredient.create('drink_id': death_in_afternoon.id, 'ingredient_id': absinthe_blanche_onefive.id)
DrinkIngredient.create('drink_id': death_in_afternoon.id, 'ingredient_id': brut_champagne.id)
DrinkIngredient.create('drink_id': death_in_afternoon.id, 'ingredient_id': lemon.id)
DrinkTool.create('drink_id': death_in_afternoon.id, 'tool_id': jigger.id)

absinthe_frappe_image = File.open('app/assets/images/absintheFrappe.jpg')
absinthe_frappe = Drink.create('name': 'Absinthe Frappe', 'directions': 'Pour the absinthe, sugar, and the water into a blender. Blend for a moment to dissolve the sugar and then, with the blender running, add 3 or 4 ice cubes through the hole in the top, pausing between cubes to let them get crushed. Blend until smooth. Garnish with lemon/mint',
'image': absinthe_frappe_image)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': metal.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': black_metal.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': death_metal.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': trap_francais.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': metalcore.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': house.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': techno.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': alternative_metal.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': classify.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': soul.id)
DrinkGenre.create('drink_id': absinthe_frappe.id, 'genre_id': chanson.id)
DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': mint.id)
DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': lemon.id)
DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': one_water.id)
DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': superfine_sugar.id)
DrinkIngredient.create('drink_id': absinthe_frappe.id, 'ingredient_id': absinthe_blanche.id)
DrinkTool.create('drink_id': absinthe_frappe.id, 'tool_id': blender.id)

gt_image = File.open('app/assets/images/ginTonic.jpg')
gin_and_tonic = Drink.create('name': 'Gin & Tonic', 'directions': 'Combine ingredients in an ice filled highball glass or wine goblet. Garnish with a lime, Juniper Berries, Grapefruit. Get creative with the garnish. Also try seasonal berries, cucumber or Rosemary',
'image': gt_image)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': pop.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': punk.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': post_teen_pop.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': viral_pop.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': edm.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': disco.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': synth_pop.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': deep_house.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': metropopolis.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': complextro.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': europop.id)
DrinkGenre.create('drink_id': gin_and_tonic.id, 'genre_id': techno.id)
DrinkIngredient.create('drink_id': gin_and_tonic.id, 'ingredient_id': american_gin.id)
DrinkIngredient.create('drink_id': gin_and_tonic.id, 'ingredient_id': four_tonic.id)

rs_image = File.open('app/assets/images/redSangria.jpg')
red_sangria = Drink.create('name': 'Red Sangria', 'directions': 'Combine brandy & honey in a large pitcher and stir until honey is dissolved. Add fruit and mash gently with the back of a wooden spoon to release juices. Add wine and stir. Cover and refrigerate for at least 8 hours and up to 48 hours. Top with soda & mint. Serve in ice-filled glasses.','image': rs_image)
DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': salsa.id)
DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': folk.id)
DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': regional_mexican.id)
DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': latin.id)
DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': latin_pop.id)
DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': spanish_pop.id)
DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': grupera.id)
DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': gospel.id)
DrinkGenre.create('drink_id': red_sangria.id, 'genre_id': mexican_indie.id)
DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': red_table_wine.id)
DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': sprig_mint.id)
DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': two_mixed_berry.id)
DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': grapefruit.id)
DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': quarter_honey.id)
DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': lemon_sliced.id)
DrinkIngredient.create('drink_id': red_sangria.id, 'ingredient_id': american_brandy.id)
